### ISSUE TITLE
remove duplicate ACL implementation

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1015]
There are currently two separate implementations of the ACL evaluation: one in the ssclj/jar module and one in the db-binding module. Extract these into a single utility library (perhaps in the auth module) to ensure that their behavior is consistent, particularly with respect to how the authentication information is passed to them (:user-name, :user-roles for db-binding; ring identity maps for ssclj/jar). 

Additionally, investigate whether the ACL evaluation is needed at all at the database binding layer. A priori this is a low-level library for the SlipStream services to interact with the underlying database. It would normally be the caller's responsibility to verify the authorization.  In any case, the caller can supply any authentication information so these additional controls have little practical value.

**Comment by konstan** [comment]
Voting for: drop the impl in db-binding, extract the one in ssclj/jar into auth.
