### ISSUE TITLE
implement $select parameter for cimi resources

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1026]
Implement the `$select` parameter for CIMI resources.  This permits choosing a subset of fields to return and also identifying which fields to update on an edit operation.

See Section 4.1.6.3 and 4.2.1.3.1 (and some other mentions of the parameter) in the [CIMI specification](https://www.dmtf.org/sites/default/files/standards/documents/DSP0263_2.0.0.pdf) to understand the expected semantics for the parameter.

**Comment by 0xbase12** [comment]
Already implemented in a duplicated ticket
