### ISSUE TITLE
change "run forever" defaults for new users

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#104]
Most users will be running predefined deployments rather than testing new deployments.  Consequently, the default values for the "run forever" flags should default to "true" for "no error occurs" and "false" for "if an error occurs".

Look in the `ExecutionControlUserParametersFactory` class for the defaults.

**Comment by schaubl** [comment]
Done

**Comment by schaubl** [comment]
With the upcoming changes this will correspond to `On Success`.
See #255 and slipstream/SlipStreamUI#184

So I'm keeping this issue open as a reminder for the new default.

**Comment by schaubl** [comment]
Done.
Closing.
