### ISSUE TITLE
implement json serialization methods for objects

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#106]
As a first step in the migration of SlipStream to clojure/Couchbase, we need to have serialization methods that will convert java objects in the data model to and from JSON representations.  These are essentially parallel methods to the existing methods in the `SerializationUtil` class.

Once the serialization methods exist, then the data objects can be moved incrementally to using the JSON representation as the default.

**Comment by schaubl** [comment]
Promoting it to Backlog.

**Comment by schaubl** [comment]
This issue continue with the #320.
