### ISSUE TITLE
[IFB] Deployment that don't disappear from active deployment after terminate

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#1077]
Hello,
I have a failed deployment (e1dd70f5-f7f9-4369-b3ab-9e46f8d3be17) that refuse to disappear from my active deployments, event after many "Terminate"
![uezz3tjrzxjk3lgg2f2ebu8fvyhz0bmxcq](https://user-images.githubusercontent.com/353767/27127076-e6efb176-50f9-11e7-8e04-efca17e9ad7e.png)

Any idea on how to remove it ?

Best regards
Bryan

See http://support.sixsq.com/helpdesk/tickets/1278

**Comment by bryan-brancotte** [comment]
Note that clicking on the "crossed ring" pictogram does not make it disappear. Nuv.la then tells me that 
"There is no instances to terminate
Error 409 - Conflict"
Best regards
Bryan
