### ISSUE TITLE
Human readable ssh key name in (openstack) clouds

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#1078]
Request from the customer.
```
Dear support

When a VM is seen on a given cloud (ifb-core-pilot) I only see the name opf the ssh key (ss-key-1496221909) which is not understandable. When the associated run (in my example https://nuv.la/run/71aff977-ffe8-44ba-809f-8f59f2252b6f) can't be accessed as I am not the owner, and identifier not found in https://nuv.la/vms?media=xml&limit=500 the only option left is to mail everyone to maybe have an answer.

Could we have a name that we can understand, like ss-key-<username>-1496221909 ? At least for openstack clouds ?

Best regards

Bryan Brancotte
```

See http://support.sixsq.com/helpdesk/tickets/1683

**Comment by konstan** [comment]
From the initial ticket in support:

I'm just trying to explain this to myself one more time. I think the main issue here is because multiple SlipStream users may use the same cloud credential (i.e., the same cloud account is shared by people from an organisation).  But on the cloud level you as the cloud site admin want to distinguish them.  However, even if (as site admin) you would know the name of the SS user (from the name of ssh key) how can you know his/her email address etc.?

Also, 
- not sure we want to de-anonymise the SS users who start VMs on clouds;
- and pure technically: the username may contain characters that cannot be part of the ssh-key name on clouds or the username length can be too long (please see attached picture to this issue https://github.com/slipstream/SlipStreamUI/issues/729).

I'm still advocating for contacting the cloud account owners directly with all the details of the VMs etc. and asking them to take actions accordingly.

RE provisioning system: Agreed that relying on the footprints that provisioners leave can be an approach to track them.  However, this may change w/o a prior notice as this is just an internal implementation detail (at least this is true for SlipStream).

**Comment by bryan-brancotte** [comment]
From the initial ticket also : 
Hi Konstantin, Hi Lionel
(It's Bryan)

I get your point Konstantin, including the username might not be a good idea. We have to find a way to find vm owner only based on slipstream UI. For Information our users __do not__ share credentials. Konstantin please note that I don't want to contact 500 users to know who is the owner of a given VM.

To find ownership I generally use https://nuv.la/vms?media=xml&limit=500 to search for the uuid of the run. In the case of the vm for the run 71aff977-ffe8-44ba-809f-8f59f2252b6f I can't find it /vms. As we do not have any other slipstream instance running it has to be nuv.la. 

> Hi Bryan,
> (It's Lionel)
> 
> I think the feature you are asking for (being able to see which SlipStream user own which VM) is already implemented.
> 
> If two or more SlipStream users share Cloud credentials or share Cloud resources (for example an OpenStack project) they will be able to see VMs of each others.
> With SlipStream you can see all VMs on the dashboard if you click on the "Virtual machines" tab.
> Once there you will be able to see VMs started by other users. You will see the short version of the deployment id and the name of the SlipStream user who started this deployment.
> If the deployment Id is "Unknown" it means that the VM was not started by this instance of SlipStream or in some cases it might mean that SlipStream failed to link the VM to a deployment.
> 
> Best regards,
> Your SixSq Support Team (Lionel)

So Lionel you tell me that when I see a VM not visible in /vms running for more an hour I can kill it ? That it is only a test vm for nuv.la ?

Best regards
Bryan
