### ISSUE TITLE
[IFB] Invalid CIMI filter

### ISSUE THREAD

**Issue by bryan-brancotte** [slipstream/SlipStreamServer#1082]
Dear support

This issue is encountered when filterting event or service offer, example are only provided for the second.

I would like to get the service offer of the ifb-core-pilot, I follow this documentation ( http://www.dmtf.org/sites/default/files/standards/documents/DSP0263_1.0.0.pdf ) page 14 line 512

I can do
https://nuv.la/api/service-offer?$filter=id='service-offer/03289337-6fa4-4657-9282-896cba082532'

but the following does not work (and should?)
https://nuv.la/api/service-offer?$filter=connector['href']='ifb-core-pilot'
image
![image](https://user-images.githubusercontent.com/11556772/27175414-746cc6ae-51bf-11e7-89ed-c935e4be348e.png)

Best regards

Bryan

**Comment by loomis** [comment]
Your filter is not valid.  Section 4.1.6.1 of the [CIMI spec](https://www.dmtf.org/sites/default/files/standards/documents/DSP0263_2.0.0.pdf) has the formal grammar; the [grammar as implemented in SlipStream](https://github.com/slipstream/SlipStreamServer/blob/master/ssclj/jar/resources/com/sixsq/slipstream/ssclj/filter/cimi-filter-grammar.txt) has been extended slightly to allow for hierarchical attributes. The levels in the hierarchy should be separated by slashes.  For the `href` attribute you want to use `connector/href`. 

Please reopen the issue if this doesn't solve your problem.

**Comment by bryan-brancotte** [comment]
Thanks !
[solution](https://nuv.la/api/service-offer?$filter=connector/href='ifb-core-pilot')
