### ISSUE TITLE
adding new connector instance and image ID to the base image requires re-saving child images

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#113]
This is needed to get the cloud connector parameters with the new cloud connector instance category to be set on the image module.

Otherwise, the image module validation code fails. Here is the example of StratusLab connector:

"Missing instance type or ram/cpu information. Please review the instance ..."

Probably the simplest solution would be to inherit from the base all the parameters for which the category is missing in the currently used one.

**Comment by schaubl** [comment]
This is a long standing bug.
We should discuss how to fix it.
Promoting to Backlog.

**Comment by mebster** [comment]
Refers to SixSq/tasklist#189 and slipstream/SlipStreamServer#125

**Comment by loomis** [comment]
Done: a detailed plan for the server and UI on what needs to be implemented.

**Comment by schaubl** [comment]
The first thing to do is inherit parameters when they doesn't exist on the image.
So this will remove the need to edit and save all image hierarchy.
I created a ticket for that: #513

**Comment by schaubl** [comment]
Done in #513
