### ISSUE TITLE
"global state" design

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1167]
Provide the design for the "global state", which will contain the instantaneous state of all cloud resources monitored by SlipStream.

**Comment by loomis** [comment]
Similarly as is currently done, the "global state" will be created and maintained by the "collector" running "describe-instance" over the managed clouds. The global state will consist of collections of CIMI resources, where each document contains the information related to a single resource.

The collector would have to perform the following actions:

 * Collect all information for each credential/cloud combination. 
 * For each identified resource (e.g. a specific VM) not currently in the global state, the collector must insert a new document for that resource in Elasticsearch. The information from the cloud must be augmented with run and service offer references, where possible.
 * For each resource that already has an entry, nothing needs to be done, although if the given entry is missing run and/or service offer references, it may try to complete them.
 * For resources within the global state that are no longer active, the associated document must be removed from the database.

The core functionality and actions are already available in the existing collector implementation, although this must be extended to provide the Elasticsearch documents, probably in addition to the current entries in the VM table in hsqldb. 

However, the current implementation should be replace for several reasons: it is quite complicated with clojure, java, and python components, can't be distributed, and is unlikely to scale well. A new implementation should consider a python-based service (as the interface the cloud is actually in python) and direct insertion of records into Elasticsearch.

**Comment by loomis** [comment]
To keep things as simple as possible initially, the only resource that will be monitored are virtual machines (as is done now).  The proposed schema is similar to the ones already proposed for the [ES accounting record](https://github.com/SixSq/tasklist/issues/1275) and for the [VM record](https://github.com/slipstream/SlipStreamServer/issues/1156).

The proposal is the following.

```json
{
  "id": "virtual-machine/867876-8768",
  "resourceURI": "http://sixsq.com/slipstream/1/VirtualMachine",

  "updated": "2017-08-15T10:00:00.0Z",
  "created": "2017-08-15T10:00:00.0Z",

  "name": "short name",
  "description": "short description",
  "properties": {
    "a": "one",
    "b": "two"
  },

  "instanceID": "aaa-bbb-111",
  "state": "Running",
  "ip": "127.0.0.1",

  "cloud": {
    "href": "credential or connector/0123-4567-8912",
    "roles": ["realm:cern", "realm:my-accounting-group"]
  },

  "serviceOffer": {
    "href": "service-offer/e3db10f4-ad81-4b3e-8c04-4994450da9e3",
    "resource:cpu": 1,
    "resource:ram": 1024,
    "resource:disk": 10,
    "resource:instanceType": "Medium"
  },

  "run": {
    "href": "run/aaa-bbb-ccc",
    "user": {
      "href": "user/test"
    }
  },

  "acl": {
    "owner": {
      "principal": "ADMIN",
      "type": "ROLE"
    },
    "rules": [
      {
        "principal": "realm:accounting_manager",
        "type": "ROLE",
        "right": "VIEW"
      },
      {
        "principal": "test",
        "type": "USER",
        "right": "VIEW"
      },
      {
        "principal": "cern:cern",
        "type": "ROLE",
        "right": "VIEW"
      },
      {
        "principal": "cern:my-accounting-group",
        "type": "ROLE",
        "right": "VIEW"
      }
    ]
  }

}
```

The first set of attributes (`id`-`properties`) are standard CIMI metadata.  The optional attributes may or may not be used, but would appear in the formal schema.

The second set (starting with `instanceID`) are specific attributes of VMs that may be useful (and are collected currently).

The `cloud` is a reference to the cloud credential or connector.  It would initially be a reference to the connector and eventually be replaced by the cloud credential once they are available.  The `roles` are intended to provide optional grouping for the accounting, independently of a particular cloud or credential. These are intended to be copied values from the credential itself (or potentially another document). 

The `run` is a reference to the SlipStream run and the `user` is a reference coming from that run. This may or not be available for a given virtual machine.

The ACL provides the following rights:

 * ADMIN: owner of the resource and full management rights
 * "test": view rights for the user, if one has been identified
 * "cern:cern", "cern:my-accounting-group": rights given to those with correct `cloud/roles`

More rights could be added, if necessary. 

The current prototype provides all the information in the above proposal, except the run.  The run information can be obtained without too much effort.

**Comment by loomis** [comment]
There are three **clients** of the global state (possibly more): 

 * "Real-time" dashboard,
 * Quota enforcement, and
 * Metering (accounting).

For the virtual machine part of the **dashboard**, the information would be a query/search over all of the virtual machine documents visible to a particular user.  Specific information about those virtual machines can be pulled directly from the document. Those tied directly to a user (as opposed to a group or role) can be selected by the existence of the `run/user/href` attribute. 

For the **quota enforcement**, three pieces of information are required:

 * Instantaneous "use" of resources for the quotas,
 * Quota definitions, and
 * Requested resources in a provisioning request.

Given this information, a determination can be made if any of the quota values would be exceeded by a particular provisioning request. 

Of the three types of information, only the first item is generated from the "global state". In this case, the information can be obtained by again querying/searching over the resources and applying the correct aggregation to a parameter (e.g. count for numbers of VMs or sum for RAM). 

The last client is the **metering**. Given that the accounting record is nearly identical to the above virtual machine document, the following would need to be done for each metering interval and for each virtual machine document:

 * Copy the virtual machine document and
 * Add a timestamp field identifying the metering interval.

For the proposed metering interval of 1 minutes, this is logically a copy of the entire global state each minute. We can probably get away with a naive, brut-force implementation initially, but should look to see if there are better ways to achieve this with Elasticsearch, perhaps copies of indexes or snapshots.

**Comment by loomis** [comment]
It seems to me that in the proposed design the "collector" implementation can follow on from the current implementation and that all of the "clients" can be implemented using searches over the database to extract the correct information efficiently. The proposed record also contains enough information to provide subviews of information by credentials, groups, roles, and users as appropriate.  **Comments welcome.**

**Comment by mebster** [comment]
**Looks good to me**  

A minor thing... if the cloud credentials are tied to a cloud connector instance, then the collector would only have to iterate over credentials.  This will come as we define the cloud credentials schema.

**Comment by cjdcordeiro** [comment]
nothing to add. The metering mechanism just needs some investigation

**Comment by elegoff** [comment]
Looks also good to me, with the same concern as above regarding the need to investigate how to make frequent copies with minimal footprint with Elasticsearch

**Comment by konstan** [comment]
LGTM.

**Comment by mebster** [comment]
I've added #1170 and #1171 to track the work on the collector.  #1171 brings the need to have a distributable collector, which means we need a scheduling and coordination mechanism.

**Comment by schaubl** [comment]
Looks Ok.
Just a question: Currently we do the describe per user per cloud so a VM can be represented multiple times in the global state (one per user who share cloud resources or share credentials).
How it should work with the new schema ? 
Should we do the same as it is now or should we try to merge them and add all users that can see the same VM in the ACL ?

**Comment by mebster** [comment]
The idea is to drop the user and only rely on `credential` (and `connector` if credentials are not tied to a cloud, but I think they should).  Then who sees what VM is just a matter of ACL.

**Comment by mebster** [comment]
As discussed yesterday, it is also important that all deployment actions go via SlipStream, including auto-scaling, such that quota enforcement is always performed.

**Comment by schaubl** [comment]
Even if we describe per credential as you suggested it is still possible that two credentials can see the same Cloud resources.
If I understand your comment correctly we should go with the 2nd solution: 
`try to merge them and add all users that can see the same VM in the ACL`
Correct ?

**Comment by schaubl** [comment]
What do we do with "unknown" VMs ? Are they part of the Global State ?
I think they should.

**Comment by loomis** [comment]
They should be treated like all other VMs.  The only difference is that they won't have a run and hence no associated user.

**Comment by mebster** [comment]
> What do we do with "unknown" VMs ? Are they part of the Global State ?
I think they should.

Also, we'll have to infer the service offer.
