### ISSUE TITLE
create benchmark resource

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamServer#1205]

**Comment by cjdcordeiro** [comment]
example of a possible service-benchmark resource:
**note that only service-offer and common fields are required**

```python
{
  "serviceOffer": {
               "href": “service-offer/e3db10f4-ad81-4b3e-8c04-4994450da9e3”,
               “resource:cpu” : 1,
               “resource:ram” : 1024,
	       “resource:disk” : 10,
               “resource:instanceType” : “Medium”,
               "connector": {
                      "href": "connector/ec2-eu-central-1"
                }
   },
  "credential": { "href": "credential/bceceb2c-c662-4dde-b6a1-8837182c1069" }
  "name": "unixbench",
  "description": "UnixBench series of benchmarks",
  "id": “service-benchmark/867876-8768”,
  "updated": “2017-08-15T10:00:00.0Z",  
  "created": "2017-08-15T10:00:00.0Z",

  "dhrystone:units": "DMIPS",
  "dhrystone:start": 1506427588,
  "dhrystone:end": 1506427978,
  "dhrystone:value": 40600.9,
  "dhrystone:freetext": "a custom note about this benchmark",
 
  "whetstone:units": "MWIPS",
  "whetstone:start": 1506427998,
  "whetstone:end": 1506428178,
  "whetstone:value": 3748.06,
  "whetstone:freetext": "a custom note about this benchmark",

   "acl": {
    ...},
   "resourceURI": "http://sixsq.com/slipstream/1/serviceBenchmark"
}
```

**Comment by loomis** [comment]
With this schema there is a one-to-one mapping between the benchmark and a single service offer. This means that the benchmark will have to duplicated if it applies to more than one service offer. Also if the referenced service offer is deleted (or deprecated), then the benchmark will not automatically be updated to point to the updated offer.  I don't have a suggestion on how to fix that, but we should just be clear about the limitations. 

Should some statement about the "authority" of the person be included specifically in the body of the document, or is it enough to identify the user through the `acl/owner/{principal, type}` enough? 

In the URI, I think the convention with the other resources is PascalCase in the URI, camelCase in the collection names/keys, and kebab-case for the URLs.

**Comment by cjdcordeiro** [comment]
> if the referenced service offer is deleted (or deprecated), then the benchmark will not automatically be updated to point to the updated offer

and it shouldn't. The updated offer will have a new benchmark.

> one-to-one mapping between the benchmark and a single service offer. 

it is actually N-to-1 no? the same service-offer will be benchmarked over and over again. 

> Should some statement about the "authority" 

as a required field? How would it be validated? 

Isn't it PascalCase for the collections? the URI is indeed, updated

**Comment by loomis** [comment]
>> if the referenced service offer is deleted (or deprecated), then the benchmark will not automatically be updated to point to the updated offer

> and it shouldn't. The updated offer will have a new benchmark.

That's fine as a policy. But the current way service offers are managed, it means that the benchmark will have a maximum lifetime of 24 hours. 

>> one-to-one mapping between the benchmark and a single service offer.

> it is actually N-to-1 no? the same service-offer will be benchmarked over and over again.

Yes, badly stated on my part.  My point was that a single benchmark cannot apply to more than one service offer.  That may be desirable, for example, for metrics like availability that would apply to all of the offers from a particular provider.  I don't have a strong opinion either way, so long as we're clear about what the limitations are. 

>> Should some statement about the "authority"

> as a required field? How would it be validated?

Presumably it would have to be linked to the user's credentials, username or similar.  This would be just to be able to say I don't trust benchmarks from "Joe Smith" but those from "Mary Cooper" are ok. This is probably a detail better left for the future. 

Yes PascalCase for the collections, but the collection tag is camelCase, e.g. `:credentialTemplates`.  Too many different ways of writing the same thing.

**Comment by cjdcordeiro** [comment]
>That's fine as a policy. But the current way service offers are managed, it means that the benchmark will have a maximum lifetime of 24 hours.

oh right. well...nothing we can do there I guess.
