### ISSUE TITLE
SSCLJ Virtual machine resource issue at update in ES with version

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#1212]
```
2017-09-27 11:27:23,125 INFO  - 200 (9 ms) GET /api/virtual-machine [internal/ADMIN] ?$filter=connector%2Fhref%3D%27connector%2Fifb-core-pilot%27+and+instanceID%3D%27cebb97b2-3750-4382-bf77-248ea16eebb9%27
                                  InternalEngine.java:494 org.elasticsearch.index.engine.InternalEngine.index
                                      IndexShard.java:556 org.elasticsearch.index.shard.IndexShard.index
                                      IndexShard.java:545 org.elasticsearch.index.shard.IndexShard.index
                        TransportShardBulkAction.java:484 org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary
                        TransportShardBulkAction.java:143 org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest
                        TransportShardBulkAction.java:113 org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary
                         TransportShardBulkAction.java:69 org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary
                      TransportReplicationAction.java:939 org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform
                      TransportReplicationAction.java:908 org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform
                            ReplicationOperation.java:113 org.elasticsearch.action.support.replication.ReplicationOperation.execute
                      TransportReplicationAction.java:322 org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse
                      TransportReplicationAction.java:264 org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse
                      TransportReplicationAction.java:888 org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse
                      TransportReplicationAction.java:885 org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse
                        IndexShardOperationsLock.java:147 org.elasticsearch.index.shard.IndexShardOperationsLock.acquire
                                     IndexShard.java:1657 org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock
                      TransportReplicationAction.java:897 org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference
                       TransportReplicationAction.java:93 org.elasticsearch.action.support.replication.TransportReplicationAction.access$400
                      TransportReplicationAction.java:281 org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun
                                 AbstractRunnable.java:37 org.elasticsearch.common.util.concurrent.AbstractRunnable.run
                      TransportReplicationAction.java:260 org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived
                      TransportReplicationAction.java:252 org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived
                           RequestHandlerRegistry.java:69 org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived
                                TransportService.java:644 org.elasticsearch.transport.TransportService$7.doRun
                                   ThreadContext.java:638 org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun
                                 AbstractRunnable.java:37 org.elasticsearch.common.util.concurrent.AbstractRunnable.run
                             ThreadPoolExecutor.java:1142 java.util.concurrent.ThreadPoolExecutor.runWorker
                              ThreadPoolExecutor.java:617 java.util.concurrent.ThreadPoolExecutor$Worker.run
                                          Thread.java:748 java.lang.Thread.run
```

**Comment by elegoff** [comment]
The above stack trace is no more present in ssclj.log (log rotation)

**Comment by elegoff** [comment]
[ssclj.log](https://github.com/slipstream/SlipStreamServer/files/1337591/ssclj.log)
Attaching relevant part of log  for example : 



> 2017-09-27 14:02:25,186 ERROR - Unexpected exception thrown: [virtual-machine][3fba61c6-3556-4ae5-83db-99ad0b457b4f]: version conflict, current version [1685] is different than the one provided [1684] 
>  org.elasticsearch.index.engine.VersionConflictEngineException: [virtual-machine][3fba61c6-3556-4ae5-83db-99ad0b457b4f]: version conflict, current version [1685] is different than the one provided [1684]
>                                   InternalEngine.java:581 org.elasticsearch.index.engine.InternalEngine.planIndexingAsPrimary
>                                   InternalEngine.java:494 org.elasticsearch.index.engine.InternalEngine.index
>                                       IndexShard.java:556 org.elasticsearch.index.shard.IndexShard.index
>                                       IndexShard.java:545 org.elasticsearch.index.shard.IndexShard.index
>                         TransportShardBulkAction.java:484 org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary
>                         TransportShardBulkAction.java:143 org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest
>                         TransportShardBulkAction.java:113 org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary
>                          TransportShardBulkAction.java:69 org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary
>                       TransportReplicationAction.java:939 org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform
>                       TransportReplicationAction.java:908 org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform
>                             ReplicationOperation.java:113 org.elasticsearch.action.support.replication.ReplicationOperation.execute
>                       TransportReplicationAction.java:322 org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse
>                       TransportReplicationAction.java:264 org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse
>                       TransportReplicationAction.java:888 org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse
>                       TransportReplicationAction.java:885 org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse
>                         IndexShardOperationsLock.java:147 org.elasticsearch.index.shard.IndexShardOperationsLock.acquire
>                                      IndexShard.java:1657 org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock
>                       TransportReplicationAction.java:897 org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference
>                        TransportReplicationAction.java:93 org.elasticsearch.action.support.replication.TransportReplicationAction.access$400
>                       TransportReplicationAction.java:281 org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun
>                                  AbstractRunnable.java:37 org.elasticsearch.common.util.concurrent.AbstractRunnable.run
>                       TransportReplicationAction.java:260 org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived
>                       TransportReplicationAction.java:252 org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived
>                            RequestHandlerRegistry.java:69 org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived
>                                 TransportService.java:644 org.elasticsearch.transport.TransportService$7.doRun
>                                    ThreadContext.java:638 org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun
>                                  AbstractRunnable.java:37 org.elasticsearch.common.util.concurrent.AbstractRunnable.run
>                              ThreadPoolExecutor.java:1142 java.util.concurrent.ThreadPoolExecutor.runWorker
>                               ThreadPoolExecutor.java:617 java.util.concurrent.ThreadPoolExecutor$Worker.run
>                                           Thread.java:748 java.lang.Thread.run

**Comment by elegoff** [comment]
Issue is not showing up in every recent logs. Closing
