### ISSUE TITLE
inherited parameters because fixed to first inherited values

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#125]
Parameters that are inherited from a parent module are given values when they are first inherited.  If the parameters in the parent module evolve, those in the child modules no longer follow the parent.

The problem is that the values from the edit form (picked up from the module itself or its parents) are stored directly into the module without checking to see if these are identical to the parent values.  If they are identical, the values should not be stored in the module and instead should inherit the values as usual.

**Comment by schaubl** [comment]
Still relevant.
This is a long standing issue.
Similar to #113.
Promoting to Backlog.

**Comment by schaubl** [comment]
To implement that we should add a checkbox called `inherited` to all `Application Parameters` to distinguish an empty value to an unset value which should be inherited.

**Comment by mebster** [comment]
Duplicates slipstream/SlipStreamServer#113
