### ISSUE TITLE
split cimi-core and optional resources

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1276]
To allow for easier reuse of the core CIMI server, split the core CIMI feature from the resource definitions.

Consider renaming the core server from ssclj to cimi in this process.

**Comment by loomis** [comment]
Given the changes to the user resource and the switch to leiningen for the build, this refactoring will have to redone based on the current code in master.

**Comment by loomis** [comment]
@cjdcordeiro Please look at the current split of resources and provide feedback.

**Comment by cjdcordeiro** [comment]
- what's https://github.com/slipstream/SlipStreamServer/tree/master/cimi-resources/test-resources for?
 - could the cloud-entry-point be moved out of the core? I know it needs to be there but it is just the naming, that might not fit all use cases
 - why do you need "job" in the core?
 - shouldn't we have all the specific session templates outside the core? (cyclone for example)
 - probably the same for credential-cloud...not sure about this one though...
 

Question: how do you configure which of the cimi-resources to include when launching the server?

**Comment by loomis** [comment]
> what's https://github.com/slipstream/SlipStreamServer/tree/master/cimi-resources/test-resources for?

This directory contains test resources used when building/debugging the service during development.  These are "java" resources like logging configuration files, not CIMI resources.  That's an unfortunate clash in names. 

> could the cloud-entry-point be moved out of the core? I know it needs to be there but it is just the naming, that might not fit all use cases

Not if you want to maintain a working service.  This is actually the only resource that is required by the CIMI spec.  It would be possible to rename the URL for this resource, but I don't see that necessarily as being worth the additional trouble. 

> why do you need "job" in the core?

It is a standard CIMI resource, but optional. It is used to handle asynchronous tasks/actions. It can be moved. 

> shouldn't we have all the specific session templates outside the core? (cyclone for example)
> probably the same for credential-cloud...not sure about this one though...

Yes, we can move some subsets (or all) of the sessions and credentials.  Moving these requires a more detailed look at the code because there are shared utilities and dependencies (for example from the middleware) that may not be easy to disentangle without some refactoring.  In any case, I can start by moving the job resource.

> Question: how do you configure which of the cimi-resources to include when launching the server?

The service tries to load all the namespaces in the `com.sixsq.slipstream.ssclj.resources` package. Those namespaces just have to be accessible from the service's classpath. Essentially you drop a jar file with the resources in the "/lib" directory of the server.

**Comment by cjdcordeiro** [comment]
ok thanks. Yes even though it is a standard CIMI resource, because it is optional, "job" can be moved. 

regarding the cloud-entry-point, let's then worry about it later.

**Comment by loomis** [comment]
> ok thanks. Yes even though it is a standard CIMI resource, because it is optional, "job" can be moved.

Yes, see #1382.

**Comment by loomis** [comment]
Moving a subset of the session, credential, and configuration resources will require a refactoring of the modules to ensure that test utilities are available for both sides and that the resource routes are cleanly separated (e.g. for github callbacks).
