### ISSUE TITLE
update authn to use cimi user resource

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1289]
Update the authentication resources and workflows to use the CIMI user resource, rather than pulling user information directly from hsqldb. 

Remove the hsqldb configuration, dependencies, and code from the repository.

**Comment by loomis** [comment]
The core of this task is a reimplementation of the namespace `com.sixsq.slipstream.auth.utils.db`, using the clojure-based resources rather than the user object from hsqldb. The three main functions are:

 * Find/set roles for the user (only the super user role from the user resource is important)
 * Find the password digest for a particular user for internal authentication
 * Create a user on a valid authentication when the user resource doesn't yet exist

The last feature may be removed in favor of explicit registration. This would simplify the logic of the authentication and reduce the "magic" in the overall user on-boarding process.

**Comment by konstan** [comment]
This was implemented as part of #1239 and merged with https://github.com/slipstream/SlipStreamServer/pull/1312.  The code cleanup in that namespace is needed though.
