### ISSUE TITLE
Implement callback cimi resource and user registration process for HBP

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#1314]
![image](https://user-images.githubusercontent.com/5518233/33600521-be8ab062-d9a9-11e7-9f0f-e5d0d53268d7.png)

**Comment by loomis** [comment]
@0xbase12 I started from your branch to create this PR. Let's discuss if the implemented behaviors are correct and if we need to add anything to the schema (e.g. a result message).  We should implement a general clean up for expired and executed callbacks (#1340).
