### ISSUE TITLE
Update the THIRD-PARTY file

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#132]
https://github.com/slipstream/SlipStreamServer/blob/master/THIRD-PARTY.txt

**Comment by schaubl** [comment]
Still relevant.
For example JClouds is not a used anymore but it's still in 74 lines of this file.

**Comment by schaubl** [comment]
Still relevant

**Comment by loomis** [comment]
IMO it would be more appropriate to just remove it, as it obviously isn't being maintained.

**Comment by schaubl** [comment]
Doesn't apply anymore
