### ISSUE TITLE
Improperly configured Image leads to a 500 error when running Deployment

### ISSUE THREAD

**Issue by zyegfryed** [slipstream/SlipStreamServer#134]
Running a Deployment module linked to an Image that is missing a Cloud Image Identifier display a 500 error in the interface.
The expected status code should be 400 with an helpful message leading the user to fix the issue quickly.

**Comment by schaubl** [comment]
This was fixed.

If we try to run an image without an id, the following message will be returned: 
```Error 409 - Conflict: Missing reference module``` 

If we try to run a deployment with a node pointing to an image without an image id, the following message will be returned: 
```Error 409 - Conflict: Node myNode refers to example/image/dead-end-image missing a machine image reference```
