### ISSUE TITLE
CIMI callback for machine/device/connector resource

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamServer#1344]
This callback needs to be able to:
1 - create a unique string
2 - push that string as an new ACL token to Consul (the CIMI server will have the proper credentials to do this action)
3 - respond to the client with the ACL token 
4 - change the respective machine/device/connector (#1343) resource's state to "Active"

(it can also simply return a Job ID if the operation is asynchronous)

**Comment by elegoff** [comment]
Closing since configuration management should not happen before long. We would open a new ticket if required
