### ISSUE TITLE
Use credential resource for S3 config

### ISSUE THREAD

**Issue by elegoff** [slipstream/SlipStreamServer#1403]
Using a AWS credential file in user home directory should be replaced by a specific credential resource
This is required by https://github.com/SixSq/tasklist/issues/1470

**Comment by konstan** [comment]
@loomis What is the timeframe for implementation of this?  We have an issue with our automated testing related to the configuration of the creds.  https://github.com/slipstream/SlipStream/issues/296 Should I still implement the config via file?

**Comment by konstan** [comment]
Just agreed with @loomis that the initial fix for 
https://github.com/slipstream/SlipStream/issues/296 will be based on the file.
