### ISSUE TITLE
logging information missing

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1438]
The CIMI server is not logging all requests to the server.  For example, user creation requests (either success or failure) and 500 failures for creating callbacks do not appear in the log file.

**Comment by loomis** [comment]
The CIMI server is currently configured to use a log4j RollingFileAppender which defaults to a maximum log file size of 10 MB and 1 backup log.  With the current logging rate of requests, this means that we save only around 40 minutes of logging information on the server (main log file and the backup file).

This is rather inadequate for debugging issues with the server.  I would propose for the request/response logging that we change to do the following:

 1) log requests at the DEBUG logging level
 2) log responses with 2xx or 3xx return codes at the INFO logging level 
 3) log responses with 4xx return codes at the WARNING logging level
 4) log responses with 5xx return codes at the ERROR logging level

Doing this and reducing the default logging level for the request/response logger to WARNING would significantly reduce the noise in the log file.

**Comment by konstan** [comment]
Mapping of req/resp to log levels looks good.

In the future, if we need service usage statistics we should either have a summariser in the server or log requests as well.  This would probably require logging to a central logging facility (like Logstash with ES behind; with a dedicated (rolling) index and with log entries 'grok'ed into docs - the latter would allow more flexible queries etc.).

**Comment by loomis** [comment]
A summary of the current statistics are available here: https://nuv.la/webui/metrics.  These were at one time pushed to graphite to keep a history.  In any case, we need a combination of a usable log file and some summary statistics.

**Comment by loomis** [comment]
In testing the logging configuration with Nuvla, changing the logging level by namespace doesn't seem to be working.  So I've changed the levels to make the normal "INFO" logging reasonable (IMO at least).

 1) log requests at the **TRACE** logging level
 2) log responses with 2xx or 3xx return codes at the **DEBUG** logging level
 3) log responses with 4xx return codes at the WARNING logging level
 4) log responses with 5xx return codes at the ERROR logging level

This means that with an INFO logging level, only 4xx and 5xx responses will be shown.
