### ISSUE TITLE
Default ACL when creating a new connector instance

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#1451]
When creating a new connector instance from the /configuration page, the new CIMI connector resource should contain an ACL rule to give VIEW permission to USER role.

**Comment by konstan** [comment]
/configuration resource is removed as part of https://github.com/slipstream/SlipStreamServer/issues/1456
Creation of connectors will only be possible from CIMI.

**Comment by konstan** [comment]
ETA for #1456 is v3.49.

**Comment by konstan** [comment]
CIMI side this was implemented with 
https://github.com/slipstream/SlipStreamServer/commit/8275e9ef457ebfbf8ef6f9c31d417f72808eccca#diff-0e95d861f0cd00ece7a9adec65e6742e
Closing.
