### ISSUE TITLE
External object resource upload Forbidden when using contentType

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#1457]
`local.cimi_add('externalObjects', {'externalObjectTemplate': {'href': 'external-object-template/report', 'runUUID':'abc', 'component':'machine', 'contentType': 'application/gzip'}})`

When I specify a contentType, I got a 403 on exoscale of S3

**Comment by elegoff** [comment]
Just a guess : could be a SignatureDoesNotMatch
It is documented that presignedURL signatures implies that :

**Comment by 0xbase12** [comment]
It's working, I missed to put the content-type in the upload request
