### ISSUE TITLE
[cimi] [job] Enhance the Job resource with "durations" attributes

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#1466]
It would be useful to have attributes showing the total duration of the job and the time spent on each state.
This will allow to do some analysis&statistics to better understand and control the flow of Jobs.

**Comment by schaubl** [comment]
Adde `★★★` and  `S04 Proposed for Sprint` for sprint because this is fully related to the work currently being done by @0xbase12 to improve the reliability of the JobEngine.

**Comment by 0xbase12** [comment]
For now why not to consider only updated - created as the full duration of the job

**Comment by schaubl** [comment]
@0xbase12 This might be an interesting value but I think the more interesting one is the time spent in "Running" state. Because the one you mentioned depend a lot on the "load" of the job-executor(s) and this "load" depend on the time jobs spend into the "Running" state. Longer execution time of a job is, lower is the job rate.

**Comment by schaubl** [comment]
Doesn't apply anymore
