### ISSUE TITLE
after sometime server stops launching async tasks

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#149]
"sometime" is about ~3 hours run-instance, describe-instance are not launched. Service restart helps.

At the same time CPU usage is 100%.

This is seen only on BB2 with 
```
[skaburskask@nlhlxlx002 ~]$ rpm -q --last slipstream-server                   
slipstream-server-2.1.7-2172.el6.noarch       Thu 27 Mar 2014 07:25:59 PM CET 
[skaburskask@nlhlxlx002 ~]$ 
```

which comes from 2.1.7 snapshot (not 2.1.7 release, where the version is 2.1.7-28).

Not seen on slipstream.sixsq.com as it still runs 2.1.6

```
[root@ip-10-34-148-97 ~]# rpm -q --last slipstream-server                    
slipstream-server-2.1.6-27.el6.noarch         Wed 26 Mar 2014 12:37:01 PM UTC
[root@ip-10-34-148-97 ~]#
```

**Comment by schaubl** [comment]
This was fixed.
