### ISSUE TITLE
metering: it doesn't work for NuvlaBox

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#1491]
Since it has been updated on 16 April, there is no data in the `metering` resource for any NuvlaBox.
It it probably related to the following commit: 9b6a506df02d26d3bad3eeb8dfdfdb522180d701

**Comment by 0xbase12** [comment]
After check, metering is working correctly. The issue was that the metering save the VM data and append to it a snapshot-time. Webui UI was using created instead of snapshot-time. This was fixed in slipstream/SlipStreamWebUI@358d9d6
