### ISSUE TITLE
NuvlaBox remote administration

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#1499]

**Comment by 0xbase12** [comment]
**Legacy:**
NuvlaBox admin UI was installed on local SS of the box.
Existing operation:
 - System info (cpu, ram, disk, usb, services status)
 - LAN, WAN, WLAN config
 - reboot, reset
Operations was proxied through cimi server to nuvlabox-admin UI without using ES DB to avoid dismatch between system config and db values. 

**Migration to remote SS**:
Questions: 
What about our discussion about ansible management for large number of NB?
How should cimi contact the box ? SSH via remote port or nearly via vpn ? Should cimi contact the box ? 
Should NB have an API key secret to access and update cimi resources, like existing VMs deployment?

**What I would like to do:**
As nuvlabox admin cimi resources are last things present in repo
https://github.com/sixsq/SlipStreamServer what about removing it and put resources in cimi-resources?

NuvlaBoxes have a collectd configured to push the load to a riemann server to say I'm there.
What about replacing it by a NB Service which pushes it's state and other info every x minutes. 
Remove riemann server and collectd from the NB and use our cimi server to push state via the SS client preinstalled in the NB.

**Comment by mebster** [comment]
Moved to NuvlaBox repo
