### ISSUE TITLE
allow user registration with exoscale coupon

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1571]
Create a user registration template that allows OIDC registration with an Exoscale coupon number.  The template should:

 * Create the Nuvla account as usual.
 * Create an Exoscale account from the coupon.
 * Create an Exoscale credential in Nuvla and give the user access to that credential.

All the above tasks should be automatic once the OIDC registration is confirmed by the user.  (That is, it should happen on the callback.)

**Comment by 0xbase12** [comment]
The code for coupon is in exoscale connector: https://github.com/SixSq/SlipStreamConnectors/blob/master/exoscale/config/

**Comment by elegoff** [comment]
Opened support ticket at Exoscale (https://portal.exoscale.com/tickets/1021655) since the former registration URL with coupon does not work anymore
