### ISSUE TITLE
get hbp user information on registration

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#1572]
For the MITREid OIDC server used by HBP another API needs to be used to get the user's registration information, notably the user's email address.

The workflow is now sufficiently different than the Keycloak workflow, that these should be separated into separate authentication methods.

For the HBP method, another URL will need to be added for retrieving the user information and will need to be used on registration.

The information from Stefano is: "In order to get user's email address in HBP you need to hit this API (https://services.humanbrainproject.eu/idm/v1/api/user/me) with the token that you got from the user. This will return an object with the follow information (image attached)."

**Comment by elegoff** [comment]
Example of returned Json : 
```{
  "id" : "306527",
  "updatedAt" : "2018-06-13T11:48:48",
  "username" : "elegoff",
  "givenName" : "Eric",
  "familyName" : "Le Goff",
  "displayName" : "Eric Le Goff",
  "title" : null,
  "profile" : null,
  "picture" : null,
  "emails" : [ {
    "value" : "elegoff@sixsq.com",
    "primary" : true,
    "verified" : true
  } ],
  "phones" : [ ],
  "institutions" : [ ],
  "ims" : [ ]
}```
