### ISSUE TITLE
Migrate to cloud-init based contextualisation in StratusLab connector

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#158]

**Comment by schaubl** [comment]
@konstan : Where are we with this issue ?

**Comment by loomis** [comment]
Connector is being discontinued.  Enhancements/fixes will not be made.

**Comment by cjdcordeiro** [comment]
@loomis maybe a similar ticket should be open, applying this cloud-init
contextualization to all connectors, following up on the HNSciCloud review

Best regards,

*Cristóvão Cordeiro*
R&D Project Manager
*LinkedIn <https://www.linkedin.com/in/cristovaocordeiro/>*

*SixSq*
*8 Rue du Bois-du-Lan*
*1217 Meyrin*
*Geneva*
*Switzerland*
