### ISSUE TITLE
can also be negative?

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamServer#1609]
https://github.com/slipstream/SlipStreamServer/blob/028f593e98359ae43eedccc38029861c59406d6f/cimi-resources/src/com/sixsq/slipstream/ssclj/resources/spec/quota.cljc#L21

How do we describe unlimited "limits"? Exoscale gives "-1" back if the quota is infinite. We should have something similar. Or we just don't create the quota resource if that's the case?

**Comment by loomis** [comment]
@cjdcordeiro If there is no limit, then there should be no quota IMO.

**Comment by cjdcordeiro** [comment]
@loomis ty. That's in fact how the quota collector is working. Closing this then
