### ISSUE TITLE
(blocking) unexpected VPN API error 503 during nuvlabox-record creation

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamServer#1714]
```Exception: Failed to do create nuvlabox-record with {'macAddress': '02:01:0a:da:ba:80', 'name': 'Kepler-196', 'formFactor': 'nano', 'refreshInterval': 30, 'owner': {'href': 'user/cjdcsixsq'}, 'organization': u'SixSq', 'identifier': 'Kepler-196'}. Reason: {u'status': 503, u'message': u'VPN-API error'}```

**Comment by elegoff** [comment]
re-Created issue in other repo (https://github.com/SixSq/SlipStreamConnectors/issues/209) . Closing this one
