### ISSUE TITLE
ensure that service urls consistently use protocol/host from proxy headers

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#177]
Currently the service uses a mix of https and http URLs depending on how the URLs themselves were generated.  The service should use headers passed from the proxy over information from the server itself.

**Comment by schaubl** [comment]
This should have been definitely fixed in 31b7b4702c591bbd706e99caf7dc530b6d490830 and in f0410dc5a12d35a8b664cd67bcf1d56a539b9264.
