### ISSUE TITLE
error running deployment when "default" cloud is selected

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#199]
When trying to run a deployment (which contains images that do not need to be built) and choosing the "default" cloud, the deployment fails with the message:
```
Error: Node master refers to image examples/images/ubuntu-12.04 missing an image id for cloud: default. Did you build it? (409 - Conflict)
```
Explicitly choosing the cloud (even if the same as the default) works correctly.

**Comment by schaubl** [comment]
This was fixed.
