### ISSUE TITLE
"Run..." button dialog has wrong default value for cloud

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#200]
When running an image with the "Run..." button, the drop-down list defaults to the first connector in alphabetical order (or at least it seems).  It should either default to the value "default" or to the connector that corresponds to the default cloud for that user.

**Comment by schaubl** [comment]
This issue is currently in progress to be fixed by slipstream/SlipStreamUI#192.

**Comment by rbf** [comment]
Result of the commits above on the UI:

![screen shot 2015-03-17 at 11 16 33](https://cloud.githubusercontent.com/assets/807084/6685102/34a27708-cc97-11e4-80fb-05698535a68a.png)

![screen shot 2015-03-17 at 11 16 58](https://cloud.githubusercontent.com/assets/807084/6685103/34a42300-cc97-11e4-9a8d-742f4edee528.png)

Moving to `To Verify`.

**Comment by schaubl** [comment]
- [ ] Add explanation for the star.

**Comment by schaubl** [comment]
Demo done

**Comment by rbf** [comment]
Changes pushed to branch `keep_running_in_run_dialog_#184`. Moving to `Done`.
