### ISSUE TITLE
Allow to change the owner of a module in certain conditions

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#208]
Currently when a module is edited and saved, the owner of the module will be changed to the account that edited the module.  This effectively locks out the original owner of the module.

The cases for changing the owner of a module should be:
- Only someone with 'edit' and 'delete' permissions should be allowed to change the owner.
- For normal users, the owner can only be changed to the person editing the module.  (That is, a normal user cannot assign the module to someone else; a normal user can only take possession of a module.)
- Administrators can change the owner of the module to any user, but only if done explicitly.  There should be no implicit change of ownership when super edits a module.

**Comment by schaubl** [comment]
This issue supersede the old issue #70.
