### ISSUE TITLE
As Alice++ I can provision a set of VMs, tolerating failures in the provisioning process, such that I can provision a large number of VMs in fewer operations

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#221]
This user story comes from CERN flagship on Helix Nebula

**Comment by konstan** [comment]
Extend to tolerate on the level of VMs instantiation.

**Comment by konstan** [comment]
Implementation is in https://github.com/slipstream/SlipStreamClient/issues/70

**Comment by loomis** [comment]
Duplicate of slipstream/SlipStreamClient#70
