### ISSUE TITLE
Carbon should start on machine reboot/restart

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#227]
Ensure installation procedures configure carbon to start on machine start

**Comment by schaubl** [comment]
Done in slipstream/SlipStreamServerDeps@474a486cc3ec832a3b70b98572c03c2a05c56210.
Now slipstream-graphite is part of the standard installation slipstream/SlipStream@cc53d798b29555086e98c8f3b171e7271a5b953a
