### ISSUE TITLE
/configuration resource doesn't support basic authentication

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#235]
Is it expected ?

**Comment by mebster** [comment]
As opposed to cookie authentication?

**Comment by schaubl** [comment]
All resources support cookie auth and basic auth but /configuration support only cookie auth because the basic authenticator is not added.
I can add it quickly, I just wanted to make sure it was not expected.

**Comment by mebster** [comment]
Ok clear. No this resource should not behave differently. The same guard method should be used when creating the router.

**Comment by loomis** [comment]
Demo is OK.  Waiting for merge.

**Comment by schaubl** [comment]
Waiting for the code review.
Demo done this morning.
