### ISSUE TITLE
Fix description of parameters "AWS Access Id" and "Secret Key" in User Profile > EC2 Connectors.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#237]
Fix description of parameters `AWS Access Id` and `Secret Key` in `User Profile`, in configuration sections of EC2 connectors:

![screen shot 2015-02-17 at 17 24 48](https://cloud.githubusercontent.com/assets/807084/6232248/07fa7f3e-b6cb-11e4-9184-15bfb9d582c4.png)

![screen shot 2015-02-17 at 17 25 02](https://cloud.githubusercontent.com/assets/807084/6232254/0bd6c18a-b6cb-11e4-89f5-313b1bdb40ac.png)

**Comment by rbf** [comment]
In the current implementation of the help-hints there is no point in having HTML into the text, because they have a `hover` behaviour, i.e. the help hint popover disappears as soon as the mouse leaves the `?` icon.

Therefore, the suggested solution is to remove HTML from the descriptions.

**Comment by st** [comment]
HTML content has been removed from info text.
New help dialogs:

<a href="url"><img src="https://cloud.githubusercontent.com/assets/16004/6602070/a6c02e5c-c819-11e4-8dc8-b9bf08007b0a.png"  width="350" ></a>

<a href="url"><img src="https://cloud.githubusercontent.com/assets/16004/6602071/a6c088d4-c819-11e4-9e87-8556774b925d.png"  width="350" ></a>

**Comment by rbf** [comment]
:smiley:  :+1:

**Comment by rbf** [comment]
As discussed yesterday with @st, now those popovers correctly parse HTML, but **only** for formatting purposes, i.e. active elements (`<a>` tags, `<button>`s and other) are not allowed because the popover disappears when the mouse leaves the `?` icon.

Therefore, in the current popover, we can use a `<code>` tag to wrap the corresponding words, instead of using single quotes, i.e. `<code>secret key</code>` instead of  `'secret key'`.

More over, I'd suggest to remove the `(required to submit to EC2)` part from the name.

See PR referenced above.
