### ISSUE TITLE
 Enforce uniqueness constraint in VM table

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#239]
Enforce uniqueness constraint in VM table - compound unique constraint (vmid,user,connector).

**Comment by st** [comment]
@konstan 
Please see https://github.com/slipstream/SlipStreamServer/pull/271

**Comment by schaubl** [comment]
Add a new unit test to check how the update method of VM.java works with the new DB constraint.

**Comment by st** [comment]
Unit test was already there (and still working). 
However, following discussion with @Konstan, a catch in caller was added to log this exception.

**Comment by konstan** [comment]
The unit test was already present as pointed out by @st https://github.com/slipstream/SlipStreamServer/blob/master/jar-persistence/src/test/java/com/sixsq/slipstream/persistence/VmTest.java#L147
We agreed on catching the exception that might come from the introduced constraint.
