### ISSUE TITLE
Consider adding node instance name or id attribute in vm element in the vms/ reouces

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#242]
Rational:
- user monitoring vms/ resource, looking for VMs in undesirable Cloud state and removing the VMs from the mutable runs. The latter requires SlipStream (node instance) id (the VM corresponds to) and the run.  At the moment user is forced to query run and look up for the id via cloud instanceId. (Reported by CERN.)

Current structure of vms/vm:

```
<vms offset="0" limit="20" count="2" totalCount="2" cloud="atos-es1">
<vm cloud="atos-es1" user="test" instanceId="32859" state="Pending" measurement="2015-02-27 13:26:31.837 CET" runUuid="3299acdd-e552-414f-9035-7c440d19e877" />
<vm cloud="atos-es1" user="test" instanceId="32860" state="Pending" measurement="2015-02-27 13:58:39.248 CET" runUuid="90b2f64c-3e99-4bdf-971c-aeeb5006eff1" />
</vms>
```

**Comment by schaubl** [comment]
This issue is part of the #281.

**Comment by schaubl** [comment]
This was done in #281
