### ISSUE TITLE
Refactor the Run resource to work better with huge Run.

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#244]
This refactor should prevent the need to loop over all nodes instances to see `where the run is` and to do the state transition.

This will allow to:
- Remove the bug where SlipStream uses 100% of the CPU and stop responding when many nodes tries to complete the state in parallel. #245 
- Reenable the overview on the Run page of big Runs.

Edit:
This refactor is needed because currently the time to "advance" the state machine is dependent to the number of VMs in the Run and the number of request to "advance" the state machine is dependant to the number of VMs as well.
So we have a complexity around O(n^2).

**Comment by mebster** [comment]
We should consider more structure in the run, including nodes and extracting state machine data into a simpler structure.

A sub node resource would allow the UI to query part of the resource.

**Comment by schaubl** [comment]
@mebster : for the sub node resource, see #247.

**Comment by mebster** [comment]
:-)

**Comment by schaubl** [comment]
This will be outdated with the CIMI deployment resource
