### ISSUE TITLE
Consider json serialisation of objects (e.g. module, run) to reduce object layout constraints  

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#246]
For the run, possibly only runtime parameters would require a one to many relationship, since runtime parameters are exposed as a sub-resource.

Candidates for sub-structure:
- run/node (and possible resource mapping)
- state machine
- modules hierarchy

**Comment by schaubl** [comment]
Related to #106.

**Comment by konstan** [comment]
Increased criticality to discuss this during the sprint planning.  

Use-case: CERN is requesting this for runs.

**Comment by mebster** [comment]
I have a prototype of this functionality where only index attributes are persisted and everything else is serialized as a json blob. I still need to overload the serializer to work with the abstract Module type.

**Comment by schaubl** [comment]
This issue continue with #320.
