### ISSUE TITLE
Allow empty ssh key when creating run

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#250]
If an ssh key is required for the cloud, create a temporary one.

Linked to: slipstream/SlipStreamUI#182

**Comment by rbf** [comment]
@schaubl 
As mentioned in [this comment](https://github.com/slipstream/SlipStreamUI/issues/182#issuecomment-77383805) of SlipStream/SlipStreamUI#182, please add the whole `user` object to the metadata provided to the UI part.

**Comment by loomis** [comment]
Please be sure that no private information (e.g. passwords) are transmitted in this object.

**Comment by schaubl** [comment]
They are transmitter from the SlipStreamServer to the SlipStreamUI but then they are not part of the generated HTML.

**Comment by schaubl** [comment]
I tested all possible behaviour and everything works as expected.

| need-ssh-access | on/true/yes  | off/others | nothing |
| ----------------------- | --------------- | ------------- | ---------- |
| with SSH key      | :white_check_mark:                     | :white_check_mark: | :white_check_mark: |
| without SSH key | :negative_squared_cross_mark:  | :white_check_mark: | :negative_squared_cross_mark: |

**Comment by schaubl** [comment]
Regarding to the discussion here slipstream/SlipStreamUI#182, I will redo the tests.

**Comment by schaubl** [comment]
Results of new tests are ok.

| bypass-ssh-check | on/true/yes  | off/others | nothing |
| ------------------------ | --------------- | ------------- | ---------- |
| with SSH key      | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| without SSH key | :white_check_mark: | :negative_squared_cross_mark: | :negative_squared_cross_mark: |

:white_check_mark: : Will accept to create the Run.
:negative_squared_cross_mark: : Will refuse to create the Run and return an error.
