### ISSUE TITLE
Improve pagination (augment limit and ensure consistency across consecutive calls)

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#260]
Two factors limit the usage of the pagination to query a big number of VMs:
* current limit for pagination server-side (20)
* order of VMs in consecutive calls is not stable.
This is worsened by a protection server side against too many requests.
See tickets for more information:
* http://support.sixsq.com/helpdesk/tickets/174
* http://support.sixsq.com/helpdesk/tickets/154

**Comment by schaubl** [comment]
This is par the the following issues:
- #281 
- #243

**Comment by schaubl** [comment]
Everything was fixed on v2.6.
- Now VMs are explicitly ordered by date added (desc).
- The limit can be increased up to 500.
- The server side protection was updated.
