### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#265]
- [x] Improve the logging format.
- [x] Allow to set a log level under INFO.

**Comment by st** [comment]
The new log format is a big improvement.
2 remarks:
* The date/time format could use ISO  8601 one (it looks like that: 2015-03-12T09:45:23.944Z). This format is used by Clojure resources (Event).
* Clojure wrapper needs to be adapted (suppress redundant display of level).

**Comment by schaubl** [comment]
@st : Can you copy your comment on the pull request #266

**Comment by schaubl** [comment]
Reviewed and merged, waiting for the demo.
