### ISSUE TITLE
Event resource part 2

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#279]
- [x] Add `/event` resource with Authentication.
- [x] Update Authorization.
- [ ] Add the ability to filter by resource id.
- [x] document it in SlipStreamDocumentationAPI
- [x] Prevent noise (event generated during unit tests)
- [x] Integration test 
- [x] Add some cases in Integration test (ACL clojure side)
- [x] Add log Clojure side 
- [ ] View events filtered by owner

Corresponding issue in the SS UI: slipstream/SlipStreamUI#229

**Comment by st** [comment]
@cal ADMIN role is now actually added when user is super. code committed.

**Comment by loomis** [comment]
Pull request #308.
