### ISSUE TITLE
When we edit&save an image which is not the latest version, the version is not given in the request. So the server compares the last version to the version being sent instead of the version that we are editing

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#295]
even if no changes was made to Build image recipes.

**Comment by schaubl** [comment]
This is a false positive.
But I found an other bug:
When we edit&save an image which is not the latest version, the version is not given in the request.
So the server compares the last version to the version being sent instead of the version that we are editing.

**Comment by mebster** [comment]
Updated the title to reflect the real issue

**Comment by rbf** [comment]
This one seems important enough to be promoted to Proposed for sprint.
Opinions?

**Comment by schaubl** [comment]
stale and will be obsoleted by the CIMI module resource
