### ISSUE TITLE
Increase the the session time

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#321]
The current value is 12 hours.
I think this value can be increase at least to 7 days.

**Comment by schaubl** [comment]
@slipstream/owners @slipstream/crew : Can you, please, suggest the expiration time you think is good for SlipStream ?

**Comment by schaubl** [comment]
I'm voting for **7 days**.

**Comment by st** [comment]
I would go for the "comfort" (7 days) now, but this should be revisited during security sprint.
Some thoughts on the subject:
http://fonicmonkey.net/2013/08/12/banish-your-session-has-expired/

**Comment by loomis** [comment]
7 days is OK for me, but agree that it should be revisited later as possibly part of an overall security review

**Comment by schaubl** [comment]
I also agree that we should revisit that.
My idea would be to have a cookie with an unlimited validity but we should keep a track of all cookies so that the user can see them and invalidate them.
Like here: https://github.com/settings/security
