### ISSUE TITLE
Add pagination to the /event resource

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#324]
E.g: `?offset=200&limit=100`
Data returned should contain the following elements:
```cfg
offset=200 
limit=100
count=43
totalCount=243
```

- [x] Implement a CIMI compliant equivalent
- [x] Do the conversion from SS representation and CIMI equivalent 

Related to: 
- #323
- #325

**Comment by loomis** [comment]
The CIMI parameters associated with paging are `$first` and `$last`.  The description can be found in Section 4.1.6.2 of the [CIMI Specification](http://dmtf.org/sites/default/files/standards/documents/DSP0263_1.1.0.pdf).  The value of the `count` attribute is defined by the standard and, I believe, corresponds to the count of items returned in the collection.  The `totalCount` could be added as a property of the collection.

I vaguely remember seeing somewhere in the specification that there can be a default value for `$last`, essentially providing a limit on the number of values returned in the collection.  However, I can't find this reference in the text at the moment.

**Comment by st** [comment]
@schaubl Organise ourselves so that we pair-program while I'm in the office.

**Comment by st** [comment]
- [ ] re-use code to validate offset, limit in ssclj redirector
