### ISSUE TITLE
Query of /events should perform ACL check at SQL level

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#325]
Related to: 
- #323
- #324

**Comment by loomis** [comment]
Can you explain why the ACL check (more than view permission) needs to be done through SQL?

**Comment by st** [comment]
It's a first coarse access control (not implemented yet) that must be performed with SQL.

**Comment by schaubl** [comment]
Currently all events are retrieved in the SQL query then they are filtered.
The idea is to do this filtering (or part of it) directly in the SQL query.
