### ISSUE TITLE
failed expectations must fail the build

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#329]
When the expectations unit tests fail, then the build process through maven must also fail.

**Comment by loomis** [comment]
The expectations tests should also respect the "-DskipTests" flag from maven if possible.

**Comment by st** [comment]
@loomis If you've got the "recipe", I'm interested.

**Comment by loomis** [comment]
Take a look at `./ssclj/jar/src/test/java/com/sixsq/slipstream/ssclj/RunExpectationsTest.java` in the SlipStreamServer repository.  It may just be a case of doing the same everywhere we're using clojure.  It also appears to correctly detect the `-DskipTests` flag, but that should be verified more carefully.

**Comment by st** [comment]
With the current pom(s).xml on master, the behaviour is OK (error inserted on purpose):
$ mvn clean install
 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-
...
[ERROR]   mvn <goals> -rf :SlipStreamCljResources-jar`

The -DskipTests and -Dmaven.test.skip=true actually skip the clojure.test and clojure expectations.
