### ISSUE TITLE
Usage records must be filtered by SlipStream origin

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#341]
As of now, the usage records store information for VMs started outside of SlipStream. This leads to usage summaries that take into account cloud usage done outside SlipStream. Which is wrong.
We should check before inserting a usage record that a corresponding run_id matches.

**Comment by st** [comment]
What about SlipStream users sharing a Cloud credential?

**Comment by schaubl** [comment]
> What about SlipStream users sharing a Cloud credential?
Currently the VMs will be taken into account for all users who share credentials.
So if userA share credentials with userB and userA has started a VM, this VM will be taken into account for userA and userB.

**Comment by schaubl** [comment]
The PR above (#355) fix the issue where VMs started outside SlipStream are taken into account for the usage records.
The change of the behaviour when users share credentials has to be discussed so I created another issue for that: #356.
