### ISSUE TITLE
User preference for usage mail summary

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#346]
The users should have the possibility to set the level of mails (containing their daily cloud usages) they receive from SlipStream:
* Never
* Daily
* Weekly (Will be greyed out to begin with)
* Monthly (Will be greyed out to begin with)

**Comment by st** [comment]
Texts to be changed for the daily usage mail.

#### Content of email sent daily
* https://github.com/slipstream/SlipStreamServer/blob/feature/real-usage/jar-service/src/main/resources/com/sixsq/slipstream/messages/Messages_en_US.xml
key : MSG_DAILY_USAGE

* some parts of the email are built outside of Messages_en_US.xml
In https://github.com/slipstream/SlipStreamServer/blob/feature/real-usage/jar-service/src/main/java/com/sixsq/slipstream/action/usage/MailUsage.java
method **usageCloud()**

####  User preference
* https://github.com/slipstream/SlipStreamServer/blob/feature/real-usage/jar-connector/src/main/java/com/sixsq/slipstream/connector/ExecutionControlUserParametersFactory.java

* https://github.com/slipstream/SlipStreamUI/blob/feature/real-usage/clj/resources/lang/en.edn
Search for 'mail-usage'

Once texts are OK in english language, I can translate them to french.

**Comment by loomis** [comment]
I've updated the descriptions.  Verify that they're OK for you and if so, translate to French (and Japanese?!).
