### ISSUE TITLE
Periodically send the daily usage mail

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#347]
A regular process (once a day) should send an email to users (if they have the correct preference set).
This email will contain:
* the aggregated usage for each cloud for the past day.
* a link to the web page containing the same information
* a link (or instructions) on how to unregister oneself from this email

The format will be HTML. (See enlive for the templating).

**Comment by st** [comment]
- [ ] put a mechanism so that job is re-entrant (no spam) but a possibility to force resend

**Comment by st** [comment]
The Java code that sends daily usage crashes SS.
Root cause is that the list of users is retrieved via User.list(). This call triggers a hibernate named query that blocks DB.

To fix that, some proposals.

#### Rewrite Java code in Clojure
pro: cleaner, toward Clojure everywhere.
cons: 
* dependency on SS process running.
* user is currently restricted to privileged users. That means that Clojure code needs to know the pwd of a ADMIN SS user.
* Clojure needs also to retrieve Configuration.getInstance().baseUrl

**Comment by schaubl** [comment]
We already had some esoteric behaviours when a Clojure code was assessing the same database as a Java code. So I would be very careful and not doing that.

I think the only way to do which ensure that it will work is **Embed current call in SS process**. 
If we want an external control of when the emails are generated, we can use a signal (ex SIGUSR1) instead of Quartz.

Before the next release, if we want to have this feature, we can do the quick Hack (stop SS, send emails and start SS).

**Comment by st** [comment]
The new Clojure code would depend on Java **resources**, not the DB.

**Comment by schaubl** [comment]
> The new Clojure code would depend on Java resources, not the DB.

Do you mean a resource like `Give me the list of users who want to get a usage report` ?
In this case there is an issue: *How to get the super password to do this request ?*

**Comment by st** [comment]
Following discussion with @loomis and @mebster, we decided to try to reproduce and investigate hibernate configuration.
SS (SaaS) was cloned to a new SS instance on exoscale.
Problem was reproduced systematically.

By changing the hibernate configuration (persistence unit 'hsqldb-schema' changed to 'hsqldb-with-c3p0-schema') on both processes (SS and daily-usage-send script), I could **not** reproduce the issue.
however, a warning is displayed: 
`INFO: Failed to get local InetAddress for VMID. This is unlikely to matter. At all. We'll add some extra randomness`

To be discussed.
