### ISSUE TITLE
<runs> element should be removed before deserialisation when Image or Deployment modules get uploaded via API

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#357]
In the first place, this fails in deserialisation with 
```
<error code="400" reason="Bad Request" detail="Invalid xml module: cannot deserialize object, with detail: Unable to satisfy @org.simpleframework.xml.Attribute(name=, empty=, required=true) on field &apos;resourceUri&apos; public final java.lang.String com.sixsq.slipstream.run.RunView.resourceUri for class com.sixsq.slipstream.run.RunView at line 1" specificationUri="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1">
Invalid xml module: cannot deserialize object, with detail: Unable to satisfy @org.simpleframework.xml.Attribute(name=, empty=, required=true) on field &apos;resourceUri&apos; public final java.lang.String com.sixsq.slipstream.run.RunView.resourceUri for class com.sixsq.slipstream.run.RunView at line 1
</error>
```
This happens when users "GET -- manually update -- PUT" Image or Deployment modules (which doesn't contradict with the API documentation at the moment).

However, taking aside the above deserialisation issue, the creation of the new versions of the runnable modules with the list of the runs from the previous one doesn't make any sense.

Sever side, the removal of the `<runs>` element can be done in `./jar-service/src/main/resources/com/sixsq/slipstream/util/module-import.xsl`.

`ss-module-{put,upload}` could also be using the same `xslt`.

**Comment by st** [comment]
- [ ] check for demo
