### ISSUE TITLE
Update configuration->target/source to 1.8 in maven-compiler-plugin

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#365]

**Comment by konstan** [comment]
Extract the version as a property to the parent pom.

**Comment by loomis** [comment]
Plugin configuration from the parent pom is merged into local configurations of the plugin. So actually the entire configuration should be extracted to the parent pom in the "pluginManagement" section.  The explicit setting of these values everywhere else (assuming they're not being overridden locally) can be removed.

**Comment by loomis** [comment]
Also reduce the dependencies in the packages to require only the JRE (headless) and not a full JDK.  This should reduce the installation time somewhat.

**Comment by schaubl** [comment]
The JRE headless will reduce a lot the size&time of the Java installation.
:+1:
