### ISSUE TITLE
Add triggering of an event in case of vertical scale request

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#378]

**Comment by konstan** [comment]
@schaubl in milestone v2.20 you've demoed #569, does it cover the vertical (and horizontal) scaling actions as well?

**Comment by schaubl** [comment]
@konstan Horizontal scaling was already covered. Vertical scaling is not covered yet.

**Comment by konstan** [comment]
@schaubl Thanks. I'm adding it to milestone v2.21.
