### ISSUE TITLE
prototype of clojure-side authentication server

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#391]
Implement the clojure-side authentication server following using the chosen libraries/frameworks and process.

**Comment by loomis** [comment]
Include discussion with team about architecture and implementation.

**Comment by loomis** [comment]
### Overview

CYCLONE will be providing a mechanism that allows the use case
applications to take advantage of federated identity.  This mechanism
will allow them to tap into their own federated identity system (based
on eduGain or Shibboleth) or to use a new federated identity system
deployed with CYCLONE components.

### Support by CYCLONE Tools

It isn't clear if the same federated identity system needs to be used
at all of the levels within the CYCLONE ecosystem: application level,
deployment level, and IaaS level.  Nonetheless, all of the CYCLONE
tools must be capable of supporting the same federated identity in
case this would be needed.

### General Architecture

The general architecture of the solution will consist of an
authentication service (per CYCLONE component) which will accept
authentication credentials from users, interact with one or more
identity providers, generate an authentication token, and then pass
that token back to the client for use with the CYCLONE component.

Although the format for the token may be different per service, there
was a general agreement to standardize on JWT (JSON Web Token) [jwt]
for the tokens, if possible.  This would allow taking advantage of the
existing token signing and validation libraries that are available in
nearly all programming languages.

Concerning the supported identity providers, there is a significant
constraint in that they must work both via the command line and via a
web browser.  Many of the current schemes for federated identity
require the use of a web browser. 

### SlipStream

The adopted infrastructure is very close to the authentication
infrastructure that we're already using on the Java side for
SlipStream.  A new prototype of this authentication service needs to
be created in Clojure for the eventual migration of the primary
service from Java to Clojure.

The prototype authentication service looks very much like a 4-part
tutorial for using the buddy clojure library [buddy] to secure
microservices ([tut1], [tut2], [tut3], [tut4]).  This is probably an
excellent starting point.

Points to keep in mind that might be specific to SlipStream and/or
CYCLONE: 

  * Need to validate the client IP address tied to the authentication
    token. 
  * Need to provide the token to the client as a secure cookie
    (i.e. the secure flag must be set so that it is only sent over
    HTTPS).
  * We need to have pluggable connections to different authentication
    providers, so a protocol is probably needed between the prototype
    and the identity providers being used.
  * The protocol may also want to provide optional methods for
    registration and resetting an account in addition to the mandatory
    authentication function(s).
  * The authentication URLs should *not* be within the `/api` part of
    the resource URLs.
  * The CIMI part of the service should only check that a valid token
    exists in the request.  Any request without a valid token should
    return a 401 status code, optionally with a Location header to
    indicate from where a token can be obtained.
  * There must be a function/method that allows a valid cookie/token
    to be generated for the orchestrator of a deployment.

If using buddy for the prototype doesn't work, then a prototype can be
implemented with a friend [friend] workflow instead.  Friend is more
common for web services in Clojure, but is fiddly and complicated.

[buddy]: https://github.com/funcool/buddy
[friend]: https://github.com/cemerick/friend
[edugain]: http://www.geant.net/service/eduGAIN/Pages/home.aspx
[shibboleth]: https://shibboleth.net
[jwt]: http://jwt.io
[tut1]: http://rundis.github.io/blog/2015/buddy_auth_part1.html
[tut2]: http://rundis.github.io/blog/2015/buddy_auth_part2.html
[tut3]: http://rundis.github.io/blog/2015/buddy_auth_part3.html
[tut4]: http://rundis.github.io/blog/2015/buddy_auth_part4.html

**Comment by st** [comment]
- [x] protocol
- [x] simple implementation using buddy for auth
- [ ] simple implementation using buddy for token creation
- [ ] refactor : split clojure in libraries : db, auth, resources, utils
- [ ] provide implementation as another REST resource (not under /api/)

**Comment by st** [comment]
Interesting pointer:
http://www.lispcast.com/clojure-web-security

**Comment by sixsq-hudson** [comment]
Very interesting indeed.

**Comment by mebster** [comment]
You say: "
The authentication URLs should not be within the /api part of the resource URLs.
"

Where do you suggest they go?

**Comment by st** [comment]
- [ ] Use existing SlipStream User table
- [ ] Expose checking function as a jar (to be used by SlipStream java server)
- [ ] Delegates Basic Authentication from Java Server to auth server
- [ ] Build encrypted/signed cookie
- [ ] Adapt LoginResource
- [ ] Adapt guard functions
- [ ] refactor : split clojure in libraries : db, auth, resources, utils
- [ ] provide implementation as another REST resource (not under /api/)
