### ISSUE TITLE
update clojure resource proxy to expose 'api'

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#394]
Update the clojure resource proxy to export all of the resources available under 'api'.  The online documentation should also be updated to reflect this.

**Comment by loomis** [comment]
Ensure that all resources are protected with paging, etc.

**Comment by st** [comment]
- [ ] check pagination by default (limit of 20 for example when no pagination)
- [ ] check filtering available.
- [ ] check authentication and ACL
