### ISSUE TITLE
The request of the event resource in HTML should use the SlipStreamUI module.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#407]
- [x] Upstream dependency: SlipStream/SlipStreamUI#296

- [x] Currently the JSON does not include the user information, so that the generated HTML looks as unlogged. Include it in the metadata so that the UI can generate the proper HTML.

**Comment by loomis** [comment]
Related to sixsq/Tasklist#354.

**Comment by rbf** [comment]
This task was finished on the context of #443.
Closing this issue.
