### ISSUE TITLE
HTML representation of event resource

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#443]

**Comment by st** [comment]
Create .../ui/event that uses ../ui/event (with the correct media type)

**Comment by st** [comment]
- [ ] Check that authentication is used (only events belonging to logged user are displayed)

**Comment by rbf** [comment]
For reference, the current implementation looks like this:

![screen shot 2015-09-04 at 17 50 22](https://cloud.githubusercontent.com/assets/807084/9688239/32d2c0a4-532e-11e5-8907-5718fdf7b796.png)

**Comment by rbf** [comment]
For reference, if the `ssclj` server (aka API Server), is not running, the `/events` page will display a `503` error page, with the corresponding message:

![screen shot 2015-09-08 at 11 46 31](https://cloud.githubusercontent.com/assets/807084/9759393/ef2a86bc-56ec-11e5-9fdc-0c57305b640b.png)
