### ISSUE TITLE
Launching a run on the UI should redirect to the dashboard instead of to the run page.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#455]
Once the dashboard is auto-refreshed and the `Terminate` action plus the `service.url` are displayed also there, it's more useful to be redirected there as it is to the run page.

Therefore, once the upstream dependencies are done, a successful `POST` request on `/run` should redirect to `/dashboard` instead of to `/run/:run-id`.

Upstream dependencies:

- **Auto refresh the dashboard**, https://github.com/slipstream/SlipStreamUI/issues/132
- **add service.url link to dashboard**, https://github.com/slipstream/SlipStreamUI/issues/400
- **Add delete button to dashboard (with warning)**, https://github.com/slipstream/SlipStreamUI/issues/395

**Comment by rbf** [comment]
@mebster 

The work for this issue was done under #457.

As per [this line](https://github.com/slipstream/SlipStreamServer/commit/e2a75317d1d1efbda8d7b1ac7bd118d4fc539b53#diff-b0373a45d862d482237f63455c03c958R93) in the commit linked from the mentioned issue, in order to make a Run launch redirect to the Dashboard, the corresponding `POST` request must include an extra parameter `redirect_to_dashboard=`, with no value.

Can you confirm?

If that's true, you can move this isssue to done or close it as duplicate from #457.

Cheers.

**Comment by mebster** [comment]
Confirmed :-)

**Comment by rbf** [comment]
This is issue is a upstream dependency of SlipStream/SlipStreamUI#422.
