### ISSUE TITLE
create proxy resource from ssclj to restlet

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#465]
Create a proxy resource that allows the RESTlet resources to be accessed from the ssclj server.  In addition to the proxy resource itself, this work must also include how to pass the authentication information from the ssclj server to the RESTlet resources.

**Comment by st** [comment]
https://github.com/http-kit/http-kit/issues/9

**Comment by sixsq-hudson** [comment]
You might try switching to the Aleph server and see if it has the same problem.  This should just be a switch from the start function in the repl.

**Comment by st** [comment]
aleph exhibits a different behaviour than http-kit but static content above a size (to be determined yet) can not be served (yet). Which shouldn't be an issue in prod environment, because nginx should take care of static content.
For http-kit, an error is returned, as aleph just hangs.

**Comment by st** [comment]
- [x] check puppetlabs clj-http-client library licence : Apache License, Version 2.0
- [ ] check /metrics and other routes are not proxied to upstream server
