### ISSUE TITLE
verify authn call out to CYCLONE fed. ID server

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#466]
Verify that the clojure authentication resources can be used to call out to the CYCLONE federated identity provider to allow for external authentication of users.

**Comment by st** [comment]
Write down a detailed plan of interaction between our server and CYCLONE server.

**Comment by loomis** [comment]
The plan must also include:
 - [ ] How the server can handle multiple authn sources (e.g. internal and CYCLONE Fed. ID at the same time.
 - [ ] Whether there is an impact on the login workflow from the UI (e.g. if a redirection to an outside service is required).
 - [ ] Whether there is an impact on the registration procedure (e.g. is a registration needed for CYCLONE or can an account be created automatically on successful login?)

**Comment by st** [comment]
Hi Stéphane,

I had a talk with Ömer yesterday and it looks like there is no easily available solution for authenticating federated user identities via command line tools based on their usernames and passwords. Of course there is Kerberos, NTLM, and Active Directory, but these are not applicable in our use case.

Generally, I see four options: emulating a webbrowser, extracting a session cookie, implementing a proxy service, and using FP accounts:

·         Emulating a webbrowser: You’d emulate the way a person would interact with the service, i.e., clicking on their IdP on the login page (keep in mind that we will add another “generic” IdP), submitting the “hidden” SAML forms (the easy part) and putting their username and password into some HTML form fields sent by the IDP (the hard part). The main challenge here is finding the right fields on the IDP login page, as each IDP uses a different form. Many use either an HTML “id” or “name” attribute containing “user” and “pass”, but not all do this. Then you’d get a redirection from the Federation Provider which you would not need to follow, but instead just use the authorization code to retrieve an identity token.

·         Extracting a session cookie: If the CLI would on a developer’s machine, you could just try to extract the session cookie from the user’s browser. This could be the easiest way.

·         Implementing a proxy service: You’d need to implement a service which creates a one-time-link for a user to click on, e.g., http://tokenservice/120758721987421093. Then the CLI would request users to click on the link. If the user clicks on the link (the browser does not need to run on the same machine), the tokenservice would login users via the Federation Provider. After this authentication is done and the tokenservice has converted the authorization code into an identity token, it would return the JSON web token or some other token as a response to the CLI.

·         Using FP accounts: Users who login via a Federated Identity through the Federation Provider always get a local account created at the Federation Provider, e.g., “tu-berlin._9e924e9bad673f00a0786facdf227b99”. They can use the Keycloak Account Manager (https://federation.cyclone-project.eu/auth/realms/master/account) to manage their own accounts and specify an Email address and an account password. You could use the Direct Access Grant (http://docs.jboss.org/keycloak/docs/1.0-rc-1/userguide/html/direct-access-grants.html) functionality to directly use a local username and password to get tokens for these local account. The biggest drawback is that you do not get any federated attributes, e.g., eduPersonPrincipalName. That means you somehow need to manage the mappings within SlipStream between the FP account “tu-berlin._9e924e9bad673f00a0786facdf227b99” and the federated account “mathias.slawik@tu-berlin.de”. Furthermore (but this is maybe a minor issue), we then cannot assure that the people who login directly still have the same roles and are still associated with their respective home organization. Also, you’d need to instruct people that they need to specify a username and password at the FP. But for the CLI this would be one of the easier ways.

I hope I was clear enough about the options you have. If you want, we can have a remote meeting between Ömer (who is mostly working on the FP), you, Cal (?), Ilke and me. Ömer is here on Mondays and Tuesdays, but can maybe also shift his hours a little.

Best regards,
Mathias

**Comment by st** [comment]
- [ ] get code
- [ ] get access-token
- [ ] get user claims
- [ ] fine-tune UI
- [ ] handle errors
