### ISSUE TITLE
Make Dashboard the welcome page.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#485]
Downstream dependency: SlipStream/SlipStreamUI#423.

**Comment by rbf** [comment]
@slipstream/owners 

We've to agree on the exact implementation of this re-routing.

In order to preserve current links to `/dashboard` (and other reasons) I'd suggest to redirect `/` to `/dashboard` (instead of routing it to `/`) and add two new routes for `/appstore` and `/projects`. Each of these new routes would display the corresponding part of the current Welcome page.

Thoughts?

**Comment by schaubl** [comment]
In this case the user may also choose which page he wants as the default.

**Comment by rbf** [comment]
:+1:

That was indeed included within the `other reasons` mentioned above. :wink:
Maybe not for this iteration, but definitely a good idea to leave the option open for it.
