### ISSUE TITLE
clean up eastwood and kibit warnings

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#487]
There are a number of warnings that are flagged by eastwood and kibit, mainly deprecated functions and overuse of threading macros.  However, there are a few potentially serious warnings about incorrect arities and bad practices.

**Comment by loomis** [comment]
As boot allows four different static analyzers to be run easily, I've investigated whether these generally provide useful information.  The four analyzers are:

 * [eastwood](https://github.com/jonase/eastwood): This generally provides good information about invalid tests (those that always pass/fail), use of deprecated functions, incorrect arity, and malformed namespace declarations.  However, it does flag "def in def" which with korma is difficult to avoid. 

* [kibit](https://github.com/jonase/kibit): Generally provides good indications on how to make the code more clear or more idiomatic.  Particularly, it flags poor use of threading macros in our code.  It also finds cases where more specific functions are appropriate (e.g. `pos?` instead of `> x 0`.

* [yagni](https://github.com/venantius/yagni): Finds unused code.  Unfortunately, it doesn't work well on our code base because we don't really have a clear entry point because of dynamic loading.  The dynamic loading of resources also means that much of the code appears dead.  This is really not useful without significant customized configuration. 

* [bikeshed](https://github.com/dakrone/lein-bikeshed): This mostly deals with code style. On our code base, it flags most files because it likes lines with fewer than 80 characters. It also checks things like doc strings, that we do not use systematically.  The one check which is potentially useful is verifying that argument names don't collide with clojure functions (e.g. `keys`, `type`, `str`).

The recommendation is that we run eastwood and kibit as part of the build automatically and fail the build if issues are found (at least once we can configure eastwood to avoid the def-in-def error).  I propose waiting to fix the identified issues until boot (or leiningen) is used for the build of the clojure code.

**Comment by rbf** [comment]
:+1:

**Comment by st** [comment]
> at least once we can configure eastwood to avoid the def-in-def error

When run with leiningen:
`lein eastwood "{:exclude-linters [:def-in-def :wrong-ns-form]}"`
Or we can choose to specify the linters we want with
`lein eastwood "{:linters [:linter1 linter2]}"`
