### ISSUE TITLE
Login username of base image is not configurable by cloud

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#491]
Example : 
On nuv.la, ubuntu 12.04 image is configured with ubuntu user for ec2, exoscale and ultimum.
Nuvlabox has ubuntu 12.04 image but the user ubuntu doesn't exist.

**Comment by loomis** [comment]
This apparently prevents a build of the image from working on the clouds where the username isn't 'root':

```
The deployment executes very well, but the build fail.

A error message is behind :
ss:abort- An error occurred while uploading script to <IP-machine>: Please login as the user "ubuntu" rather than the user "root".

I run them on the same cloud.
```

**Comment by schaubl** [comment]
The workaround is to copy the component and change the `Login username` under the `Operating System Details` section.

To fix this issue we have to implement these two features:
1. [ ] Allow to define the login username per cloud
2. [ ] Stop building via ssh and use the node executor insead

**Comment by 0xbase12** [comment]
Wanted to work on it to make it possible to set it at runtime, but noticed that this is different from cloud parameters. The login username is an attribute of an image and can only be set in base images.

If we move the login username to cloud parameters, this will impact following module:
- SlipStream Client (Node instance should take it from cloud parameters and if not available should search in image attribute for retro-compatibility
- SlipStream Server 
  - to make it settable at runtime
  - to remove it from image attribute (what this will impact?)
  - add a method as for security group for cli which will be used by all connectors.
  - update get login username method used by cli (Simple run and build image)
- SlipStream connectors to add this to the cli params
- SlipStream UI, remove `Operating System Details` to avoid confusion of users and move the platform to `Cloud Image Identifiers and Image Hierarchy`
