### ISSUE TITLE
Improve display of metrics in usage email

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#493]
Improve display of metrics in usage email

**Comment by st** [comment]
Use sensible units (hours/days) instead of minutes.

**Comment by st** [comment]
![screen shot 2015-10-13 at 11 10 00](https://cloud.githubusercontent.com/assets/16004/10450527/13685f90-719b-11e5-8a75-a71bb461dc68.png)

The metric values are formatted with the following heuristic:
* VM value : presented by hour
* RAM  value : presented by GB hour
