### ISSUE TITLE
Due to SIP on 'el capitan', move linked connectors CLIs from /usr/bin to another location

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#495]
SIP on `El Capitan` doesn't allow to write to `/usr/bin` http://www.infoworld.com/article/2988096/mac-os-x/sorry-unix-fans-os-x-el-capitan-kills-root.html  It's still possible to write to `/usr/local/bin`.

To simplify the development on Mac, we need to move our hardcoded CLI location away from `/usr/bin`.
Simplest solution would be: make `/usr/local/bin/` as default in https://github.com/slipstream/SlipStreamServer/blob/master/jar-connector/src/main/java/com/sixsq/slipstream/connector/CliConnectorBase.java#L52

All connector RPM POMs should be updated.

**Comment by mebster** [comment]
Ensure documentation on updating path is provided.

**Comment by konstan** [comment]
First have a discussion on the overall strategy.
