### ISSUE TITLE
Provide inherited targets with each image

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#501]
This can be built on the fly when GETing an image

**Comment by rbf** [comment]
:+1:
For the use case we are working out for the CYCLONE project with i2CAT, it would be _very_ useful to have the inheritance of deployment scripts.

**Comment by mebster** [comment]
I've got this partially done in the json-persistence branch.  I'll show Lionel this afternoon.

**Comment by rbf** [comment]
@schaubl: Are you aware of the work done on the [`feature/json-persistance-and-serial`](https://github.com/slipstream/SlipStreamServer/tree/feature/json-persistance-and-serial) branch? Can we schedule this issue for next iteration?

**Comment by mebster** [comment]
I didn't have time to show @schaubl last Friday.  But if you look at the ImageModule.java fill you'll find a transient 'targets' field, aimed at hosting on the fly constructed map of Target objects. The Target class includes the concept of inheritance.  I didn't have time to implement the filling of the targets field, but it would be similar to the parameters.

The idea of having a transient field, is that it gets serialised, but not persisted.  So we don't to store the inherited structure in the DB, since it can change depending on parenting changes.  Instead it is re-built every time the resource is retrieved (GET).  Also, not storing the structure also gives us much more freedom in the layout of the structure, without hibernate constraints.

Hope this helps.
