### ISSUE TITLE
Empty abort message on an authentication error while provisioning Orchestrators in multi-site deployment

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#504]
![screen shot 2015-10-21 at 11 40 39](https://cloud.githubusercontent.com/assets/353767/10633424/e11972b2-77ea-11e5-9e7b-ee74bd2101cc.png)

Log does contain the error message captured from `stderr`

![screen shot 2015-10-21 at 11 36 56](https://cloud.githubusercontent.com/assets/353767/10633667/7e8b5622-77ec-11e5-9cad-c3073e0f60b2.png)

It should have appeared on the abort message.

**Comment by schaubl** [comment]
The abort message probably contains the right error message but the UI is not displaying it because the browser consider the content as HTML thanks to < and >.

**Comment by rbf** [comment]
@schaubl comment is probably right. Can you share the link to such a run or inspect the alert HTML?
