### ISSUE TITLE
SS server can be installed and used on system where SELinux is enabled

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamServer#505]

**Comment by 0xbase12** [comment]
**Following command should be run to make slipstream server compatible with SELinux.**

```shell
setsebool -P httpd_run_stickshift 1
setsebool -P httpd_can_network_connect 1
semanage fcontext -a -t httpd_cache_t "/tmp/slipstream(/.*)?" 
restorecon -R -v /tmp/slipstream || true
```

**Also updating slipstream server install script :**
https://raw.githubusercontent.com/slipstream/SlipStream/release-latest/install/slipstream.sh
Other files ?

** My proposition**:
To make sure that SlipStream service will not have down time because of selinux forbide access, I suggest to enable SELinux in permissive mode for 3 weeks on nuv.la. Permissive mode will allow access to everything as if SELinux is disabled but will log every "access denied" as if SELinux was in enforcing mode.

**Comment by 0xbase12** [comment]
connected to https://github.com/slipstream/SlipStream/pull/103

**Comment by schaubl** [comment]
Top-level issue: SixSq/tasklist#755
