### ISSUE TITLE
use clojure authentication system

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#509]
Make all of the changes necessary to switch to using the clojure authentication server by default.  The server can EITHER run as a separate server OR run within the clojure server for CIMI resources.  In both cases the authentication code must be packaged into separate jar files from the other resources.

If running as a separate server, the code base should be refactored to avoid duplicating the core server code.  Also the separate server must have a separate RPM package with all of the supporting files (`init.d` script, default configuration file, etc.).

Review the following and update accordingly:
 - [ ] Administrator Guide information concerning the properties of the service, location of log files, etc.
 - [ ] Quick installation procedure, scripts, and documentation.
 - [ ] Reference configuration and SlipStream deployment tests from Jenkins.

**Comment by st** [comment]
- [ ] passphrase
- [ ] `lein install` OK, but not `mvn install`
- [ ] common dependency to all server modules to centralize clojure server definition
