### ISSUE TITLE
make clojure server the primary SlipStream server

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#510]
As Java-based resources can now be proxied from the clojure server, make the clojure server the primary SlipStream server.  At a minimum, the `nginx` configuration will need to be updated to point to the correct server.  There may also be changes necessary to the quick installation script and documentation. After making this change, all of the build and deployment jobs within Jenkins must be verified.

**Comment by st** [comment]
- [ ] nginx configuration
- [ ] quick installation script
- [ ] documentation
- [ ] check builds
