### ISSUE TITLE
Server silently fails to login the user if the `ssclj` server is not running.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#529]
An `5xx` error is expected in the same way that we have a `Wrong credentials` error if the password is wrong.

**Comment by st** [comment]
@rbf : new specific alert when auth server not started:

<img width="975" alt="screen shot 2015-11-18 at 19 27 03" src="https://cloud.githubusercontent.com/assets/16004/11252263/8523cef6-8e35-11e5-9711-fac168198670.png">

**Comment by rbf** [comment]
:+1:
