### ISSUE TITLE
SS startup configuration file /etc/default/slipstream is no longer a configuration in RPM

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#535]
`SS v2.19.1` 
This was noticed on BB where we maintain a separate configuration for HNX skin

```
[root@bluebox ~]# rpm -qf -c /etc/default/slipstream | grep '/etc/default/slipstream'
[root@bluebox ~]#
```

**Comment by konstan** [comment]
I propose to close this issue as non existent.  @loomis please check below.

Here is the misunderstanding that led to submitting the issue.

1. `/etc/default/slipstream` is the link to `/opt/slipstream/server/etc/default.slipstream`.  The latter is marked as configuration in the RPM.  So, the files to look for differences after the RPM upgrade for the "incoming" changes are `/opt/slipstream/server/etc/default.slipstream.rpm*` (not `etc/default/slipstream.rpm*`).

2. The initial check for the file being a configuration in the RPM should have been done this way
```
[root@ip-10-73-188-103 ~]# rpm -qf -c /etc/default/slipstream | grep $(readlink /etc/default/slipstream)
/opt/slipstream/server/etc/default.slipstream
[root@ip-10-73-188-103 ~]#
```

**Comment by loomis** [comment]
Thanks for the explanation.  Closing...
