### ISSUE TITLE
Self-registration is not working

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#539]
This is the link sent to the user
https://localhost:8182/action/1b092b67-9355-4ece-ae01-bc3d34e84229/confirm

`localhost:8182` instead should point to the public hostname.

DONE:
- [ ] functional self-registration test in CI is present

**Comment by st** [comment]
Quick fix on nuv.la and BB : bypass Clojure proxy.
Fix available here:
https://github.com/slipstream/SlipStreamServer/commit/17df7bcc6df31cf2dcc924947ec9da13ed0fd222
