### ISSUE TITLE
Metering is empty

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#540]
Cause of bug:
Queries to `metrics/render` are double url-encoded.
Correct query:

```
 ...      GET     /metrics/render target=keepLastValue(slipstream.super.usage.disk-gb.*%2C24)&from=-3840s&format=json ...
```

The special characters `(` and `%` in this request are wrongly re-urlencoded by clojure proxy.

**Comment by 0xbase12** [comment]
deprected
