### ISSUE TITLE
defined recipes are not transferred to node

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#545]
For an application component what has the pre-install, install, and post-install recipes defined, the recipes appear in the run XML representation but are not transferred to the node and are consequently **not** run on the machine.

The `/tmp` are on the deployed machine looks like:
```
# ls -l 
total 12
-rw-rw-rw- 1 root root 1127 Nov 24 06:18 machine_report_2015-11-24T061801Z.tgz
-rw-r--r-- 1 root root  130 Nov 24 06:17 slipstream.setenv
-rwxr-xr-x 1 root root  395 Nov 24 06:17 tmpJoCAtl
# cat tmpJoCAtl 
#!/bin/bash -xe

# get the value from slipstream
title="`ss-get title`"

# replace the title in the welcome page
sed -i "s/__TITLE__/${title}/g" /var/www/html/index.html

# provide a link to the webserver through slipstream
hostname=`ss-get hostname`
link=http://${hostname}/
ss-set ss:url.service ${link}

# provide status information through web UI
ss-display "Webserver ready on ${hostname}!"# 
```
showing that the deployment recipe is there but not the others.

The scripts are actually defined in the XML representation of the run [run.txt](https://github.com/slipstream/SlipStreamServer/files/42421/run.txt).

**Comment by konstan** [comment]
https://nuv.la/module/loomis/ubuntu-12.04-script-problem/2367 is the native image with cloud image IDs defined on it.  This simple run (image run) contains the following

```
      <entry>
         <string>machine:run-build-recipes</string>
         <parameter name="machine:run-build-recipes" description="Define if the SlipStream executor should run build recipes." category="General" mandatory="false" type="String" readonly="false" order_="0" order="0">
            <value><![CDATA[false]]></value>
         </parameter>
      </entry>
```

It looks as if the server-side assumes that if cloud image IDs are present on the image module there is no need to run `prerecipe` and `recipe` scripts (`run-build-recipes`).

https://github.com/slipstream/SlipStreamServer/blob/master/jar-persistence/src/main/java/com/sixsq/slipstream/persistence/ImageModule.java#L146

**Comment by schaubl** [comment]
>It looks as if the server-side assumes that if cloud image IDs are present on the image module there is no need to run prerecipe and recipe script
@konstan : Yes, you're right. Having a native image with "build" script is a very bad idea and should be forbidden because once the image has been build the image-id will be replaced by the new one and the original one will be lost.
Anyway this issue doesn't apply anymore because with the new feature of "inherited recipes" the parameter `run-build-recipes` is not used anymore.
