### ISSUE TITLE
missing project name for openstack connector gives misleading error message

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#547]
If the user forgets to add the project name in the configuration, then deployments fail with an error like "undefined instance type".  This is very misleading and points the user to the wrong place to search for the problem.  The error should indicate that there is a problem with the configuration of the connector.

**Comment by schaubl** [comment]
@loomis: I haven't seen this exact behaviour because if the project name is not provided or wrong, it will return an error like `Wrong credentials`.

I improved the error messages so that users will know where to look to find the issue.
