### ISSUE TITLE
registration works but redirects to an error page

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#57]
The registration workflow now actually registers a new user after confirmation of his email address.  However when clicking on the "register" button, an error page (404) comes up with the user at the URL https://slipstream-server.example.org/null.

**Comment by schaubl** [comment]
I think this issue is not valid anymore.
@loomis @rbf @mebster : Can you confirm and close the issue ?

**Comment by rbf** [comment]
:+1:
