### ISSUE TITLE
support github authentication

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#577]
Enhance the new authentication server to support the GitHub authentication workflow.  This is an intermediate step to supporting the slightly more complex workflows of Shibboleth and other federated identity services.

**Comment by st** [comment]
- [x] prototype of communication with github (`oauth2`protocol)
- [ ] when auth server absent : un-handled  error
- [ ] fine-tune UI
- [ ] when already logged-in with Github
