### ISSUE TITLE
Reduce verbosity of "daily-usage-emails-cron.log"

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#617]
The file `/var/log/daily-usage-emails-cron.log` on nuv.la grows very fast. Currently the whole email body is included when logging an email sending.

**Comment by st** [comment]
https://github.com/slipstream/SlipStreamServer/blob/master/jar-persistence/src/main/java/com/sixsq/slipstream/util/Notifier.java#L93
