### ISSUE TITLE
Edugain SSO integration

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#618]
Discuss with Switch how to integrate with Edugain.

**Comment by loomis** [comment]
Determine what is the better solution:
 - [ ] accessing eduGAIN (shibboleth) directly with nginx and shibboleth module or
 - [ ] replicating the CYCLONE Keycloak deployment and using the existing integration.

**Comment by loomis** [comment]
Information about the Keycloak deployment is available here: https://github.com/cyclone-project/cyclone-federation-provider.

**Comment by 0xbase12** [comment]
@loomis should this ticket be closed?

**Comment by loomis** [comment]
Yes.  This was implemented by @cjdcordeiro in other tickets.
