### ISSUE TITLE
deployment must stop if bootstrap script fails

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#62]
Currently (at least for the StratusLab connector) if the bootstrap script fails, then the orchestrator will remain running but the deployment does not advance.  If an error occurs when executing this script, the logs should be recovered to the server, the machines torn down, and the deployment put into a terminal state.

**Comment by schaubl** [comment]
This was done.
The state machine will continue up to the `Ready` state so reports will be send during `Sending reports`.
Then depending on the parameter `keep-running` the Run will be terminated or will stay in `Ready` waiting for debug.
