### ISSUE TITLE
GET of ss:groups RTP in the run's global namespace fails

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#627]
On the CLI (or on the deployment script) it results in an endless waiting loop:

```
# ss-get ss:groups
Waiting for ss:groups
Waiting for ss:groups
```

Directly `GET`ing https://nuv.la/run/554772fe-ed2e-45fb-97c0-bc925e32cc23/ss:groups?ignoreabort=true returns in an `Error 412`:

![screen shot 2016-02-15 at 17 47 46](https://cloud.githubusercontent.com/assets/807084/13054879/4bed0c98-d40c-11e5-8f09-f859bf3d87d6.png)

## Workaround in `python`

``` python
from slipstream.SlipStreamHttpClient import SlipStreamHttpClient
from slipstream.ConfigHolder import ConfigHolder

call = lambda command: subprocess.check_output(command, shell=True)

# FIXME: "ss-get ss:groups" does not currently work.
#    groups = call("ss-get ss:groups")

call('touch /tmp/slipstream.client.conf')
ch = ConfigHolder()
ssc = SlipStreamHttpClient(ch)
ssc._retrieveAndSetRun()
groups = ssc.run_dom.attrib.get('groups')
```

For reference, bug discovered (and the workaround) with @konstan.

**Comment by konstan** [comment]
Just a clarification.  The wait by CLI is probably not endless, but rather the default 60 sec.
