### ISSUE TITLE
Introduce ss:ips RTP in the run's global namespace

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#628]
Very often the application developer has to know the IP addresses of all deployment VMs. As of now we could find them out by parsing the `ss:groups`<sup>1</sup> , then the node's `<nodename>:ips` and finally the `<nodename>.<id>:hostame`.

Since this is a fairly common need, we should be able to provide a direct way to get all IP addresses with e.g. `ss:ips`. Arguably we could provide more run details in an easily parsable json-like object `GET`able at once.

---

<sup>1</sup> There is currently a bug preventing `GET`ing the `ss:groups` though: https://github.com/slipstream/SlipStreamServer/issues/627

**Comment by isartcanyameres** [comment]
For Cyclone applications with networking services, it would be common that the application developer has to know which component instances <nodename>.<id> compose the deployment.

Getting their IP addresses is probably the most common use case for that, but being able to get the tags each instance has will be another interesting use case.
So IMHO it would be interesting to have a direct way to get all component instances in the deployment e.g. ss:instances returning a coma separated list of <nodename>.<id>.

With that set, either retrieving an instance run details from an easily parsable json-like object GET able at once, or retrieving each property individually have almost same value to me.
