### ISSUE TITLE
Include detailed stats about cloud usage in the dashboard metadata

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#642]
- [x] Include the number of apps (deployments or images) running on each cloud
- [x] Include the number of unexpected (aka unknown) vms seen by the user's `describe-instance` on each cloud (see details of each of the unexpected cases in the description of the issue https://github.com/slipstream/SlipStreamUI/issues/542)
- [x] Include an global entry to add up stats for all clouds (to generate the `All clouds` gauge). This is currently done by both the UI module and the client. Doing it directly on the server would simplify it.
- [x] Remove the `runs` element from the metadata since it's [not used](https://github.com/slipstream/SlipStreamUI/blob/master/clj/test/slipstream/ui/models/dashboard_test.clj#L65-L74) and represents potentially an expensive call.

---

@loomis FYI we discussed with @schaubl and @mebster about https://github.com/slipstream/SlipStreamUI/issues/542 and realised that we need some work server side. This is the task for that, assigned to @schaubl and for the current iteration (`v2.24`).

**Comment by mebster** [comment]
We could also add a future 'cloud status', which in the case of NBs would indicate when a given NB is online, or if we detect a problem with a cloud endpoint.

**Comment by rbf** [comment]
This would only make sense if the status is checked and updated on each request, i.e. on each automatic dashboard refresh every 10 seconds. If we check the _status_ of the cloud only twice a day, this info would not be representative in the context of the dashboard gauges.

Further there is a a further task (https://github.com/SixSq/tasklist/issues/630) to consider adding a "status" page on nuv.la, where this info would rather be gathered.

**Comment by mebster** [comment]
My point was about providing high level info on the gauge, including possibly status, once the data is available. How the data is collected is another issue.

**Comment by rbf** [comment]
@schaubl Thanks for the push of the branch [`slipstream/SlipStreamServer/issue_#642-dashboard-detailed-usages`](https://github.com/slipstream/SlipStreamServer/tree/issue_%23642-dashboard-detailed-usages) which allows me to continue the work on https://github.com/slipstream/SlipStreamUI/issues/542. I was about to check it out and realised that it's on version [`2.24-SNAPSHOT`](https://github.com/slipstream/SlipStreamServer/blob/023c8cf68cc81c2c252a137958737491d5706091/war/pom.xml#L12) while `master` is at [`2.23.2-SNAPSHOT`](https://github.com/slipstream/SlipStreamServer/blob/99aa396091e1e1d340004978f4d3ac65fed0ca76/war/pom.xml#L12).

FYI I'm checking out the branch and changing the versions locally to match `2.23.2-SNAPSHOT`.

@loomis @konstan @schaubl When and how are the versions planned to be aligned?
