### ISSUE TITLE
Changes done outside of SlipStream prevent close of usage records

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#643]
If the instance type of a VM is changed *outside* of SlipStream, we are currently unable to close the previous value.
For example, the VM for that run (https://nuv.la/run/cd8f5a49-820c-4f79-9669-0a3b2ac8cc79#slipstream+slipstream-1) was changed (instance type) in exoscale dashboard.
The corresponding usage record was left open, even after the VM was terminated.

**Comment by konstan** [comment]
What about cpu/ram(/disk size?) metrics that can change during the lifetime of VM same way as instance-type, i.e. "outside" of SlipStream?  I'm not sure this is covered.
