### ISSUE TITLE
Cyclone external authentication failed

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#654]
Error message is

```
External authentication failed
SlipStream was unable to obtain information to create a corresponding user. Please check that a login and an email are returned by your authentication provider.
```

**Comment by st** [comment]
Fixed on Cyclone side.
- [x] TUB user 
- [ ] hesge.ch (Khaled)  (name edugain_123123123123)
- [ ] UvA.nl mail sent

**Comment by st** [comment]
email sent to Ömer on march 23 regarding 500 error.

**Comment by 0xbase12** [comment]
@loomis should this ticket be closed ?

**Comment by loomis** [comment]
Yes.  I don't know if there is more to follow up and this will be replaced by the newer implementation shortly.
