### ISSUE TITLE
add/remove acl principal list to stored documents

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#667]
Create a standard function that create the field "_acl-principals" in the **stored** documents.  This field contains a list of all of the named principals in an ACL.

Also create a standard function that strips this field from the document before returning it to the client.

The "_acl-principals" field will be used to filter documents based (with a TermsMatch) on a user's groups/roles when querying for documents.

**Comment by st** [comment]
- [ ] check update operation (does not return modified document yet)

**Comment by loomis** [comment]
The PR looks good except for a couple of small things.  Take a look to see if you want to change something.  After changes (if any), you can go ahead and merge the PR.

As you've done with the elasticsearch performance ticket, please add a comment with the conclusions from the test, including a list of things that would be necessary to include this in the standard CIMI server.

**Comment by st** [comment]
#### Conclusions

* ACL filtering (coarse grain) is easily implemented (technical hidden fields `_acl-*`)
* performances not impacted
* IMO, fine grain ACL should also be done at this layer.
* `binding` protocol is documented with `ring` responses. Not done yet.
* from a migration point of view (hsqlb -> elastic search), nothing to change (re-use of ACLs already present in documents)
* Should we enforce the presence of Identity information in request, or just return an empty result when absent?
* Currently using `user-name` and `user-roles` as identity in `options` map. Subject to change. 
* `(def ^:private query-no-result (ef/term-query "id" ""))` is the trick to build a query with no results on purpose. Not super elegant, and may return results. (on the condition ES db is corrupted, i.e data with blank :id present)

**Comment by st** [comment]
- [ ] exception if no empty identity provided
- [ ] systematically add ADMIN with ALL right when inserting
