### ISSUE TITLE
rename ServiceInfo and Attribute resources

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#668]
Change ServiceInfo and Attribute resources to ServiceOffer and ServiceAttribute.  Fix all of the code that references them.

**Comment by loomis** [comment]
The resource tag for these resources must be "serviceOffers" and "serviceAttributes", in camel case and plural.

**Comment by st** [comment]
- [x] name changes (ServiceInfo and Attribute resources to ServiceOffer and ServiceAttribute)
- [ ] adapt tag for resources
- [ ] migration for BB
