### ISSUE TITLE
Some usages are not included in the daily usage email.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#683]
I found an example of a usage on one cloud which appears on https://nuv.la/usage as expected but did not appear on the usage digest email of the corresponding day.

I shared the details directly with @st.

**Comment by st** [comment]
Some investigations with @rbf example were made.
(Bug is : Only 4 of 5 summaries are displayed in the email.)
* usage records are OK (lifecycle events trigger correct insertions in DB)
* usage summaries are OK (CRON jobs compute correct summaries : 5 for that day/user/frequency)

Suspect is the call made to retrieve all usages from DailyUsageSender.
This API call may hit the limit of 20 elements returned by default, thus truncating some usages.
To be confirmed.

From logs, here is the API call made:
`http://localhost:8201/api/usage?%24filter=start_timestamp%3D2016-04-04+and+end_timestamp%3D2016-04-05+and+%28user%3D%27konstan%27+or+user%3D%27sixsq_dev%27+or+user%3D%27cedricseynat%27+or+user%3D%27lionel%27+or+user%3D%27rob%27+or+user%3D%27stef%27+or+user%3D%27test%27+or+user%3D%27segi2cat%27+or+user%3D%27oleg%27%29`
This actually returns only 20 elements for a `count` with a `count` (prior pagination) of 23.

**Comment by st** [comment]
demo:
```
[root@nuv ~]# diff /tmp/usage-{20,10000}.txt
20a21,23
>     "id" : "usage/2aa7b793-8e52-4657-8b5f-868a8433b210",
>     "id" : "usage/6cdf5d88-de9e-43b3-b195-496101b2246a",
>     "id" : "usage/ff053740-2fea-4a9a-955c-a046734377e0",
```
`usage/2aa7b793-8e52-4657-8b5f-868a8433b210` is rob's missing email. (2 others belong to test).
