### ISSUE TITLE
Pending VMs do not appear to be counted in the usage data provided to the UI by the server.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamServer#687]
Pending VMs are those running for less than 15min and still without run id.

![screen shot 2016-04-07 at 14 54 40 copy](https://cloud.githubusercontent.com/assets/807084/14352040/ca894faa-fcd2-11e5-90ab-9776419929be.png)

The underlying `?media=xml` data matched the displayed values.

NB: For reference, the `Pending` flag in the bottom VMs table is handled directly by the UI module, not be the server. The corresponding Vm is [flagged as `Pending` directly by the UI module](https://github.com/slipstream/SlipStreamUI/blob/0718bb0baaa07ce3ad7a77b3a1313fca602d294f/clj/src/slipstream/ui/models/vms.clj#L18) (not by the server) and [displayed as such](https://github.com/slipstream/SlipStreamUI/blob/0718bb0baaa07ce3ad7a77b3a1313fca602d294f/clj/src/slipstream/ui/views/tables.clj#L854).

**Comment by schaubl** [comment]
This is not a bug. It appeared as a bug because of slipstream/SlipStreamUI#579
