### ISSUE TITLE
Implement Riemann stream to process and publish connector availability metric to Service Catalog

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#708]
Part of US https://github.com/SixSq/NuvlaBox/issues/115

**Comment by st** [comment]
remarks on implementation choices:
* *synchronous* calls when updating state 
* no use of time window in riemann (would avoid flapping)
* send only state changes

**Comment by st** [comment]
- [ ] install locally riemann (brew)
- [ ] first version of logic with fake HTTP calls
- [ ] real HTTP calls to "talk" to ServiceOffer resource
