### ISSUE TITLE
create /ui/placement resource

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#735]
- needs authn: use auth as impl. example (not CIMI resource)
- contact PRS micro-service
- initial implementation 
  - empty in -> clouds out

**Comment by konstan** [comment]
Depends on #736

**Comment by st** [comment]
- [x] new service in ssclj : /ui/placement (echo service)
- [x] java proxy to this new service
- [ ] contact PRS-lib
- [ ] JS calls /ui/placement on local server (no cross site calls)

**Comment by st** [comment]
JS code is manually tested in a developer console:

```javascript
SlipStream.request
  .put("/ui/placement")
  .data({clouds:["aa", "bb"]})
  .serialization("json")
  .dataType("json")
  .onSuccess(function(x){console.log(x["clouds-mockup-1"]);})
  .send()
```

With this call, we see that the mockup `/ui/placement` is used.
