### ISSUE TITLE
result of build is not copied to image if run continues on success

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#75]
If the user mistakenly launches a build when he has the "continue on success" flag set, then the generated image of a build is never copied back to the image module.  This is particularly painful because the process takes a long time and there is no way from the user interface to manually set the identifier of the generated image.

The build should either copy this value back on success in all cases or ignore the "continue on success" flag.

**Comment by schaubl** [comment]
`Continue on success` doesn't apply to a Build.
The value of `keep-running` for a Build is always `never` because it makes no sense to keep it running because the user cannot SSH into the orchestrator and only the orchestrator can access the machine used to build the new image.
