### ISSUE TITLE
add ssh links to interface

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#77]
All of the information to create links in the SlipStream interface for connecting to machines via ssh is available (hostname and username).  These links would save the user from having to look up and type the machine address and would make the overall user experience better.

Safari is configured by default to handle ssh URLs.  Other browsers would need to have a handler configured, but the necessary configuration isn't difficult.

The feature should allow users to enable/disable the links as an option in their user profile.

**Comment by schaubl** [comment]
Done
