### ISSUE TITLE
install packages should fail on errors

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#781]
The `install packages` phase should fail if the installation command fails.  Currently, a component that adds an invalid package will silently ignore the error and continue. (E.g. an ubuntu image with 'unknown-package-name' to be installed.)

The `apt-get` command itself fails:

```
# apt-get install unknown-package-name 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package unknown-package-name
# echo $?
100
# 
```

but the command we use:

```
/bin/sh -c export DEBIAN_FRONTEND=noninteractive; apt-get -y update || (sleep 60; apt-get -y update); sleep 15; apt-get -y --force-yes install unknown-package-name; sync; sleep 5
```

returns 0 even on an error.

**Comment by sandrineperrin** [comment]
They are two solves to obtain exit value on install package command.

You can save exit value in variable ($res)

```
/bin/sh -c export DEBIAN_FRONTEND=noninteractive; apt-get -y update || (sleep 60; apt-get -y update); sleep 15; apt-get -y --force-yes install unknown-package-name ; res=$? ; sync; sleep 5

# echo $? 
0 # exit value for sleep command

# echo $res
100 
```

or you can stop execution at the first command which fail : replace ';' by '&&'
```

/bin/sh -c export DEBIAN_FRONTEND=noninteractive; apt-get -y update || (sleep 60; apt-get -y update) && sleep 15  \ && apt-get -y --force-yes install unknown-package-name && sync && sleep 5

# echo $?
100 
```

Command sync and sleep are ignored

**Comment by loomis** [comment]
There is a worry raised by Lionel that detecting a non-zero return code will fail when a package has already been installed.  As a quick test, I checked this for Ubuntu 14.04 (`apt-get`) and with CentOS 7 (`yum`), both return a zero error code when asking for a package that has already been installed.  A systematic check should be performed to ensure that there are no issues with this.

**Comment by loomis** [comment]
Using the following command for CentOS 6 and CentOS 7:
```
$ yum install -y emacs-nox && yum install -y emacs-nox && echo 'OK'
```
Installs the package and prints 'OK' on both operating systems. 

On an Ubuntu 12.04 minimal VM, running the following command twice returns zero return codes in both cases:
```
/bin/sh -c export DEBIAN_FRONTEND=noninteractive; apt-get -y update || (sleep 60; apt-get -y update) && sleep 15 && apt-get -y --force-yes install openjdk-6-jre  && sync && sleep 5 ; echo $?
```
The first invocation actually installs the Java package.

On Ubuntu 14.04 and 16.04 minimal VMs, running the following command twice returns zero return codes in all cases:
```
/bin/sh -c export DEBIAN_FRONTEND=noninteractive; apt-get -y update || (sleep 60; apt-get -y update) && sleep 15 && apt-get -y --force-yes install openjdk-8-jre  && sync && sleep 5 ; echo $?
```
The first invocation actually installs the Java package on the VMs.

At the moment, I don't see any reason not to check the return code from the `apt-get` command.
