### ISSUE TITLE
store/load ServiceConfiguration entity to/from Elasticsearch as json

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#817]

**Comment by konstan** [comment]
Demoed from branches https://github.com/slipstream/SlipStreamServer/tree/issue_%23817-serviceconfig-to-es
and 
https://github.com/slipstream/SlipStreamConnectors/tree/feature/service-config-in-es

on Fri Sep 16 CEST 2016

**Comment by konstan** [comment]
TODO

- [ ] add editable `description` parameter for the connector instance itself with the default `Instance of connector {{connector name}}`,
- [ ] migrate other connectors (build list of current connectors and vote for the most important ones (probably the ones that are now used on nuv.la)),
- [ ] finalise `ss-config` utility that should load documents to DB (ES), use edn format for the input,
- [ ] updated SlipStream deployment regarding the new way of the service configuration.

**Comment by konstan** [comment]
Here is the list of the first candidate connectors for migration to ssclj service.  Those are the ones currently used on nuv.la

- [ ] azure
- [ ] cloudstack
- [ ] ec2
- [ ] exoscale
- [ ] nativesoftlayer
- [ ] nuvlabox
- [ ] opennebula
- [x] openstack (done in https://github.com/slipstream/SlipStreamConnectors/tree/feature/service-config-in-es)
- [ ] stratuslabiter

**Comment by loomis** [comment]
My personal opinion is that azure and nativesoftlayer could be deferred, if necessary.

**Comment by mebster** [comment]
Yes.  But then we need to remove these connectors from Nuvla.

**Comment by mebster** [comment]
An important issue raised and briefly discussed during the demo is support for i18n.  I've created an new issue to track that: https://github.com/SixSq/tasklist/issues/862.

**Comment by konstan** [comment]
Demoed on Fri Oct  7 2016.
- building of enterprise SS from the feature branches
- deployment of 3.13 from enterprise snapshots
- migration of configuration from nuv.la to the deployed instance
- new ss-conf* utilities for the service configuration migration and update of the service configuration.

TODO

- [ ] documentation of migration procedure (to go to release notes)
- [ ] documentation of the new server configuration method and used utilities with examples.
