### ISSUE TITLE
move or update usage summarizer utility

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#846]
The usage summarizer needs to be compiled so that it can be started from the command line.  However, compiling it (with all of their dependencies) bloats the size of the jar file and can potentially cause version conflicts with other jars. 

Either:
 - [ ] Move it to a separate module and create an uber jar to call it, or
 - [x] Keep it in the ssclj jar, but load the implementation dynamically from the main function.

**Comment by mebster** [comment]
Test: check that the usage email is sent

**Comment by st** [comment]
- [ ]  Keep it in the ssclj jar, but load the implementation dynamically from the main function.
- [ ] Test on nuv.la that `create*.sh` scripts work
