### ISSUE TITLE
[ssclj/tools] optimise the size of jar providing ss-config* CLI

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#862]
At the moment it gets build as uberjar in assumption that it can be ran fully independently.  The size of the resulting jar is ~60MB and it takes a lot of IO disk/network in handling it in CI/Nexus.

**Comment by konstan** [comment]
@mebster if you are considering this as an impediment - I could start working on this right away.  In fact, we've discussed this issue yesterday with @loomis There are different options on how to resolve it.  For example, the one proposed by @loomis is to not to create the uberjar at all and use boot on the target machine to bring the dependencies and run the ss-config* scripts.

**Comment by mebster** [comment]
How long do you think it'll take @konstan?

**Comment by konstan** [comment]
I'll stop building the uberjar and set the classpath of the ss-config* utils to contain `/opt/slipstream/ssclj/lib/ext/` (this is where all the ssclj server deps are and all that the utils need.)  Checked with @loomis 
I start working on this now.

**Comment by konstan** [comment]
@mebster Sorry I didn't see your previous comment.   I think that the "boot on config host" based solution may take 4, while the "`/opt/slipstream/ssclj/lib/ext/` in classpath" is 1.
