### ISSUE TITLE
Support cpu/ram/disk server side as module parameters

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#863]

**Comment by st** [comment]
- [ ] ? UI: order of image module parameters in creation section.
* currently:  Nb CPU, Disk (GB), Volatile extra disk in GB, Network type, RAM (GB)
* should be: Nb CPU, RAM (GB), Disk (GB), Volatile extra disk in GB, Network type

- [ ] pricing. exoscale: take disk price into account

- [ ] placement service: returns the list of service-offers above given (cpu/ram/disk) for all clouds. For each cloud, the smallest are returned. (a service offer is smaller than another one when its CPU, RAM and Disk are all equal or smaller than CPU, RAM and Disk of the other. Usually, we expect only one smallest when service offers can be ordered with previous definition)

**Comment by mebster** [comment]
Comments following demo:

- [ ] for Open Nebula connector, remove module CPU/RAM (could move to the SlipStream/SlipStreamServer)

**Comment by st** [comment]
Here is a proposal to display additional information regarding connectors:

<img width="608" alt="screen shot 2016-11-08 at 18 07 32" src="https://cloud.githubusercontent.com/assets/16004/20109011/8be47bb6-a5de-11e6-8f2d-e7a5aff6bd21.png">
