### ISSUE TITLE
price estimation should take into account orchestrator especially with scalable deployment

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#864]
At the moment, when starting an app with all the component multiplicities set to zero (which is a valid case) - the estimated price is reported as zero as well.  This is not true, as there will be orchestrator deployed, which incurs cost.

<img width="1296" alt="screen shot 2016-10-25 at 14 20 36" src="https://cloud.githubusercontent.com/assets/353767/19685840/b8d8f528-9abe-11e6-9672-4e531f175706.png">
<img width="1296" alt="screen shot 2016-10-25 at 14 21 20" src="https://cloud.githubusercontent.com/assets/353767/19685849/bfd81ab6-9abe-11e6-9e7b-3860ce828489.png">

**Comment by st** [comment]
- [ ] add a node "orchestrator" for scalable deployments
- [ ] find a way to retrieve correct instance type for this pseudo-node.
- [ ] process this new component in response by adding this price as a fixed cost.

**Comment by loomis** [comment]
These points have been done.
