### ISSUE TITLE
formalize resource via a clojure protocol

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#867]
Currently, the CIMI resource implementations are a collection of multi-methods and fields that allow for the autoloading of the resources, proper routing of requests, and reuse of standard CRUD functions. 

Unfortunately, the methods/fields that need to be specified are poorly documented and the (over)use of multi-methods makes the implementations less maintainable.  Moving to a protocol would make the resource interface clear and make it easier to add new resources quickly.

**Comment by loomis** [comment]
A draft of a protocol is available here: https://github.com/slipstream/SlipStreamServer/blob/master/ssclj/jar/src/com/sixsq/slipstream/ssclj/resources/common/resource_protocols.clj. 

All feedback on this protocol from everyone is welcome, including naming, organization, location, functionality, etc.

**Comment by mebster** [comment]
Good stuff. 

1. What's the HTTP standard response for POST to create a new resource?  Where should the user recover the new UUID from?
2. The delete function is associated with HTTP DELETE requests right?  Should be mentioned in the doc

Should this protocol also address:
- [ ] ACL
- [ ] group/role assignments
- [ ] i18n

On the namespace:
I still think that 'ssclj' in the namespace is not necessary.  Why should SlipStream (ss) and the language (clj) be in the path?  'slipstream' is already in the path. As we transition towards an all clojure solution, we could use something smaller:
com.sixsq.slipstream.ssclj.resources.common.resource-protocols -> slipstream.server.resources.common.resource-protocols?  'server' implies that 'client' also exists, but I'm not sure about that.  We don't need com.sixsq, as slipstream is sufficiently unique now.

**Comment by mebster** [comment]
Another thought... would this protocol also support none REST resources like a future placement api?

**Comment by loomis** [comment]
As the namespace doesn't affect the protocol definition, I've created a separate issue for discussion of that: SixSq/tasklist#924.

**Comment by loomis** [comment]
The routing of HTTP actions to the various SCRUD methods is defined by the CIMI standard.  See Section 4 of the [CIMI Specification](https://www.dmtf.org/sites/default/files/standards/documents/DSP0263_2.0.0.pdf).  Specifically for a create request, an HTTP 201 (created) response with the created resource identifier in a "location" header is expected on success.  The "delete" action is indeed mapped to the HTTP DELETE function.  I've updated the documentation in the protocol methods to reflect this.

**Comment by loomis** [comment]
The ACL is an integral part of the resource and can be created/modified through the standard CRUD operations. Consequently there is no need for a separate set of functions for ACL management.  The exception is the "add-acl" function that allows a resource to modify the default ACL used for new resources.  However, this is an "internal" function used by the standard SCRUD function implementations and not exposed through the web application. 

Managing the ACL separately from the resource would be another possible implementation. This would allow "pure" CIMI resources (the ACLs are a SixSq extension to the schema). The downside is that any action would require at least two queries to the database: one for the resource and another for the ACL.  This would be particularly costly for "search" operations as the join of the "read" permission and the query filters would like have to be done manually.

**Comment by loomis** [comment]
The permissions associated with the roles (groups, attributes, etc.) are explicitly part of the ACL.  The roles held by the user are part of the authentication token that is passed as part of the request.  So I don't see the need for any group/role assignment functions in this protocol.  Perhaps, I've misunderstood what you had in mind with your suggestion above.

**Comment by loomis** [comment]
@mebster CIMI doesn't specify anything related to internationalization. What are you expecting to internationalize and how would you see that fitting into the protocol?

**Comment by loomis** [comment]
The placement service API is by nature not a REST-oriented API:  it calculates placement options for a  particular application/user.  Consequently, this protocol, centered around CIMI resources, doesn't lend itself well to this case.  One could imagine extracting the subset of useful functions for this case (essentially `initialize`, `routes` and `validate`) as a separate protocol. However, given that the number of placement "functions" is likely to be limited, I'm not sure that the overhead of defining a protocol for this is worth the overhead.

**Comment by mebster** [comment]
As you're suggesting, it's better if the protocol is focused and only does one thing well, which in this case is define the interface contract for RESTful resources.  For none (e.g. RPC-like) REST resources, specific semantic makes more sense, with or without a protocol to define it.

For the ACLs, I'm not completely clear how this works, hence the question.

For i18n, I just want to make sure we're not blocking a path to multi-language support.
