### ISSUE TITLE
If cloud VM ID of orchestrator is not available at the deployment termination request, SS should enqueue the request and re-try it internally with a timeout

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#872]
Users complain about orchestrator (and then maybe VMs) running after placing the deployment termination requested "too soon".

**Comment by konstan** [comment]
To prevent this from happening, the suggestion is do not allow to place the deployment termination request when 

- the deployment is still in `Initializing` state, but `orchestrator` (app deployment) or `machine` (comp deployment) VM ID is not yet set.

This implies the following changes.  Until the above condition holds:

- UI: `Terminate` button is not active;
- API: `DELETE` on `run/<uuid>` returns 409 with `Inconsistent state for deployment termination. Cloud VM ID of orchestrator/machine should be set.`.

**Comment by st** [comment]
Looks OK. 
Protection on API (409 returned) would also prevent UI from early termination even if button active all the time, right?

**Comment by konstan** [comment]
@st Yes, that is correct.

**Comment by sixsq-hudson** [comment]
Is there an impact in our CI pipeline?  What is causing this early termination that's causing this issue if leaked resources?

**Comment by konstan** [comment]
@mebster There should be no impact on the CI pipeline per se.  We will have to update Clojure API to take into account new 409. 
I don't know (yet) the cause of the early termination.  My first guess is -- we run out of time and at some point terminate the deployment with still running tests; where some of the tests might be starting to provision new VMs.  Still this has to be checked.
