### ISSUE TITLE
Rename REST resource usage to usage-summary

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#879]
- [x] `/api/usage ` -> `usage-summary`
- [x] `/usage` -> `/usage-summary` (URL in Java server is renamed but label stays unchanged)
- [x] in JSON responses `usages` -> `usage-summaries`
- [x] in JSON responses `usage` -> `usage-summary`
```
"usage-summaries" : [ {
   ...
    "usage-summary" : {
    ...
     },
    ...
  } ],
 ...
```
- [x] migration: rename existing documents
- [x] migration: improve : work by bulk, add option to script
- [x] use new resource in consolidation processes
- [x] use new resource in UI
- [ ] write migration documentation

A new resource `usage-summary` is created. A migration allows to copy existing `usage` documents in this new resource.
`usage` resource can then be deleted.

**Comment by konstan** [comment]
@st Can this issue be closed?

**Comment by st** [comment]
@konstan no, it was not merged yet.

**Comment by schaubl** [comment]
Related branch: [issue_#879-rename-usage-summary](https://github.com/slipstream/SlipStreamServer/tree/issue_%23879-rename-usage-summary)

**Comment by loomis** [comment]
Won't implement at this time.  See PR comments for rationale.
