### ISSUE TITLE
debug unit test failures on centos 7

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#919]
The build job for SlipStreamServer has failing unit tests on CentOS 7. The tests do not fail on Mac OS.

**Comment by konstan** [comment]
Just noticed this.  This is due to a different order of the tests.  And yes, the ES DB bootstrap is needed.  There is this helper method to solve the issue.

```
import com.sixsq.slipstream.es.CljElasticsearchHelper;
...
        @BeforeClass
	public static void setupClass() throws ConfigurationException, SlipStreamException {
		CljElasticsearchHelper.createAndInitTestDb();
       ...
       }
```
