### ISSUE TITLE
validate "Cloud Configuration" parameters for the cloud instance are present

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#96]
There should be a validation before each deployment checking if the images have all the required parameters for the cloud instance in the "Cloud Configuration" parameters section.
Discovered via: after running 

```
ss-module-upload -u sixsq -p xxx --endpoint https://localhost ./*.xml
```

image of the service-testing tutorial was updated without merging the already defined connector instances into the new image version. 

[connector instances on the image version 67]
![screen shot 2013-12-03 at 15 58 26](https://f.cloud.github.com/assets/353767/1665123/2b25b70c-5c32-11e3-9cd7-5f1b0fd89d22.png)

[connector instances on the previous image version 21]
![screen shot 2013-12-03 at 16 47 42](https://f.cloud.github.com/assets/353767/1665146/6a56da78-5c32-11e3-8d59-7d6e4440470e.png)

This lead to deployment failures on Orch side which was failing to get the cloud instance related parameters (size/etc.).

**Comment by schaubl** [comment]
Related to #66
